"""OrgElMorph course - Computational C3: figures + numbers.

Writes the octree-mesh figure and the dt-ladder figure into
../../latex/figures/, and the measured macros into
../../latex/numbers/c3.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from adaptivity import (octree_refinement, adaptive_time_stepping,
                        bdf2_variable_order)

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "c3.tex")


def octree_figure(o, fname):
    """Draw the adaptive element grid: each element as a square sized by
    its edge length, colored by refinement level -- small squares hug the
    circle, big squares fill the bulk."""
    fig, ax = plt.subplots(figsize=(5.4, 5.2), dpi=150)
    c, h, lv = o["centers"], o["hs"], o["levels"]
    order = np.argsort(lv)                       # draw coarse first
    for i in order:
        x0, y0 = c[i] - h[i] / 2
        ax.add_patch(plt.Rectangle((x0, y0), h[i], h[i], fill=False,
                                   ec=plt.cm.viridis(lv[i] / lv.max()),
                                   lw=0.5))
    th = np.linspace(0, 2 * np.pi, 200)
    ax.plot(0.5 + 0.30 * np.cos(th), 0.5 + 0.30 * np.sin(th), "r-",
            lw=1.5, label="interface (refined here)")
    ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.set_aspect("equal")
    ax.set_title(f"Octree refinement: {o['adaptive_nodes']} nodes vs "
                 f"{o['uniform_nodes']} uniform\n"
                 f"({o['node_savings']:.1f}x fewer dofs, same finest $h$)")
    ax.legend(loc="upper right", fontsize=9)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def ladder_figure(t, fname):
    fig, ax = plt.subplots(figsize=(6.6, 4.4), dpi=150)
    ax.plot(t["ts"], t["dts"], "o-", color="C0", ms=4, lw=1.5)
    ax.set_xlabel("time $t$"); ax.set_ylabel(r"accepted step $\Delta t$")
    ax.set_yscale("log")
    ax.set_title(f"Adaptive time step over a quench "
                 f"({t['span']:.0f}x range, {t['savings']:.0f}x "
                 f"step savings)")
    ax.grid(alpha=0.3, which="both")
    ax.annotate("violent onset:\n$\\Delta t$ small", xy=(t["ts"][0],
                t["dts"][0]), xytext=(0.15, t["dts"].min() * 1.4),
                fontsize=9, color="C3")
    ax.annotate("coarsening:\n$\\Delta t$ grows", xy=(t["ts"][-1],
                t["dts"][-1]), xytext=(0.30, t["dts"].max() * 0.5),
                fontsize=9, color="C0")
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def sci(val):
    m, e = f"{val:.1e}".split("e")
    return rf"${m}\times10^{{{int(e)}}}$"


def write_numbers(o, t, b):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    lines = [
        "% AUTO-GENERATED by gen_figures.py - do not edit.",
        # octree
        mac("CthreeAdaptNodes", f"{o['adaptive_nodes']:,}"
            .replace(",", r"{,}")),
        mac("CthreeUniformNodes", f"{o['uniform_nodes']:,}"
            .replace(",", r"{,}")),
        mac("CthreeNodeSavings", f"{o['node_savings']:.1f}"),
        mac("CthreeElemSavings", f"{o['elem_savings']:.1f}"),
        mac("CthreeMaxLevel", f"{o['max_level']}"),
        # temporal ladder
        mac("CthreeNadaptive", f"{t['n_adaptive']}"),
        mac("CthreeNfixed", f"{t['n_fixed']:,}".replace(",", r"{,}")),
        mac("CthreeSpan", f"{t['span']:.0f}"),
        mac("CthreeSavings", f"{t['savings']:.0f}"),
        mac("CthreeDtMin", sci(t["dt_min"])),
        mac("CthreeDtMax", sci(t["dt_max"])),
        # BDF2 order
        mac("CthreeVarOrder", f"{b['order']:.2f}"),
        mac("CthreeConstOrderLo", f"{b['const_coeff_order'][0]:.2f}"),
        mac("CthreeConstOrderHi", f"{b['const_coeff_order'][1]:.2f}"),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    o = octree_refinement(device=args.device)
    t = adaptive_time_stepping(device=args.device)
    b = bdf2_variable_order(device=args.device)
    octree_figure(o, "c3_octree.png")
    ladder_figure(t, "c3_ladder.png")
    write_numbers(o, t, b)


if __name__ == "__main__":
    main()
