"""OrgElMorph course - Differentiable D6: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and numbers into
../../latex/numbers/d6.tex.  Same core as run.py, but the noisy-recovery
curve is averaged over several noise realisations (nseeds) for a smooth
statistical trend.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from learn_energy import learn

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d6.tex")


def _sci(val, digits=2):
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    Kfirst, Klast = r["Ks"][0], r["Ks"][-1]
    improve = r["errsK"][Kfirst] / max(r["errsK"][Klast], 1e-30)
    lines = [
        "% AUTO-GENERATED by differentiable/06 gen_figures.py - do not edit.",
        mac("DsixSnaps", f"{r['nst']}"),
        mac("DsixNseeds", f"{r['nseeds']}"),
        mac("DsixNoise", f"{r['noise']:g}"),
        mac("DsixAzero", f"{r['a_clean'][0]:.5f}"),
        mac("DsixAone", f"{r['a_clean'][1]:.5f}"),
        mac("DsixErrClean", _sci(r["err_clean"], 1)),
        mac("DsixLossClean", _sci(r["loss_clean"], 1)),
        mac("DsixKfirst", f"{Kfirst}"),
        mac("DsixKlast", f"{Klast}"),
        mac("DsixErrKone", f"{r['errsK'][Kfirst]:.3f}"),
        mac("DsixErrKlast", _sci(r["errsK"][Klast], 1)),
        mac("DsixImprove", f"{improve:.0f}"),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def recovery_figure(r, fname):
    """Left: the recovered f'(c) (clean) lying exactly on the truth
    c^3-c, with the wrong initial guess for contrast. Right: the noisy
    recovery error falling as more snapshots are used."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.2), dpi=150)

    cc = r["cc"]
    a0 = (0.5, -0.5)
    fp_guess = a0[0] * cc ** 3 + a0[1] * cc
    ax1.plot(cc, r["fp_truth"], "-", color="k", lw=3.0,
             label=r"truth  $f'(c)=c^3-c$")
    ax1.plot(cc, r["fp_rec"], "--", color="C3", lw=2.0,
             label="recovered (clean)")
    ax1.plot(cc, fp_guess, ":", color="C0", lw=1.6,
             label="initial guess")
    ax1.set_xlabel("$c$")
    ax1.set_ylabel("$f'(c)$")
    ax1.set_title("Learned free-energy derivative vs. truth")
    ax1.legend()
    ax1.grid(alpha=0.3)

    Ks = np.array(r["Ks"])
    errs = np.array([r["errsK"][K] for K in Ks])
    stds = np.array([r["errsK_std"][K] for K in Ks])
    ax2.errorbar(Ks, errs, yerr=stds, fmt="o-", color="C2", lw=1.6,
                 capsize=4, label=f"mean over {r['nseeds']} noise seeds")
    ax2.set_yscale("log")
    ax2.set_xlabel("number of snapshots $K$")
    ax2.set_ylabel(r"recovery error $|a-a^{\rm truth}|_\infty$")
    ax2.set_title(f"More snapshots sharpen the fit "
                  f"($\\sigma={r['noise']:g}$ noise)")
    ax2.legend()
    ax2.grid(which="both", alpha=0.3)

    fig.suptitle("Learning the free energy from morphology snapshots",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    ap.add_argument("--nst", type=int, default=10)
    ap.add_argument("--nseeds", type=int, default=12)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = learn(level=args.level, nst=args.nst, nseeds=args.nseeds,
              device=args.device)
    recovery_figure(r, "d6_recovery.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
