"""OrgElMorph course - Differentiable D5: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and numbers into
../../latex/numbers/d5.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from crystallinity import sensitivity

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d5.tex")

LABEL = {"dh": r"$\Delta h$", "Tm": r"$T_m$", "dsig": r"$\Delta\sigma$",
         "eps2": r"$\varepsilon^2$", "L": r"$L$"}
MAC = {"dh": "DfiveGradDh", "Tm": "DfiveGradTm", "dsig": "DfiveGradDsig",
       "eps2": "DfiveGradEps", "L": "DfiveGradL"}


def _sci(val, digits=3):
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    worst = max(r["rel"].values())
    lines = [
        "% AUTO-GENERATED by differentiable/05 gen_figures.py - do not edit.",
        mac("DfiveSteps", f"{r['n_steps']}"),
        mac("DfiveJ", _sci(r["J"])),
        mac("DfiveFrac", f"{r['frac']:.4f}"),
        mac("DfivePsiTgt", f"{r['tgt_psi']:g}"),
        mac("DfiveRelFD", _sci(worst, 1)),
    ]
    for nm in r["names"]:
        lines.append(mac(MAC[nm], _sci(r["g_adj"][nm])))
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def field_figure(r, fname):
    fig, ax = plt.subplots(figsize=(4.6, 4.0), dpi=150)
    im = ax.imshow(r["psi_field"], origin="lower", cmap="magma")
    ax.set_title(f"crystallinity field $\\psi$ "
                 f"($\\langle\\psi\\rangle={r['frac']:.3f}$)", fontsize=11)
    ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label=r"$\psi$")
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def sens_figure(r, fname):
    """The five crystallisation sensitivities (adjoint bars, FD dots).
    Their relative sizes rank which knobs move the crystallinity most."""
    names = r["names"]
    x = np.arange(len(names))
    adj = [r["g_adj"][nm] for nm in names]
    fd = [r["g_fd"][nm] for nm in names]
    fig, ax = plt.subplots(figsize=(7.2, 4.4), dpi=150)
    ax.bar(x, adj, 0.55, color="C0", label="adjoint")
    ax.plot(x, fd, "D", color="C3", ms=8, label="finite diff")
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels([LABEL[nm] for nm in names], fontsize=13)
    ax.set_ylabel(r"$dJ/dp$   ($J=\frac{1}{2}|\psi_N-\psi^\star|^2$)")
    ax.set_title("Crystallinity sensitivity to the thermodynamic knobs")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    ap.add_argument("--steps", type=int, default=3)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = sensitivity(level=args.level, n_steps=args.steps,
                    device=args.device)
    field_figure(r, "d5_crystallinity.png")
    sens_figure(r, "d5_sensitivity.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
