"""OrgElMorph course - Physics P4: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p4_*.png and ../../latex/numbers/p4.tex.  The
signature figure is the composition trajectory on the Gibbs triangle.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from ternary import build_mesh_dm, run, bary_to_xy

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p4.tex")


def _triangle(ax):
    v = np.array([[0, 0], [1, 0], [0.5, np.sqrt(3) / 2], [0, 0]])
    ax.plot(v[:, 0], v[:, 1], "k-", lw=1.2)
    ax.text(-0.02, -0.03, "solvent", ha="right", va="top", fontsize=9)
    ax.text(1.02, -0.03, r"$\phi_1$ (polymer)", ha="left", va="top",
            fontsize=9)
    ax.text(0.5, np.sqrt(3) / 2 + 0.02, r"$\phi_2$ (fullerene)",
            ha="center", va="bottom", fontsize=9)
    ax.set_aspect("equal"); ax.axis("off")


def fig_gibbs(r, fname):
    ns = sorted(r["snaps"])
    fig, axes = plt.subplots(1, len(ns), figsize=(3.4 * len(ns), 3.4),
                             dpi=150)
    for ax, n in zip(axes, ns):
        _triangle(ax)
        p1, p2 = r["snaps"][n]
        x, y = bary_to_xy(p1, p2)
        ax.scatter(x, y, s=2, c=p2, cmap="plasma", alpha=0.35,
                   vmin=0, vmax=0.9)
        ax.set_title(f"t = {n:.3g}", fontsize=11)
    fig.suptitle("Composition trajectory on the Gibbs triangle: the "
                 "cloud opens along a tie-line as the blend demixes",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_fields(r, fname):
    p1, p2 = r["snaps"][max(r["snaps"])]
    side = r["side"]
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 4.0), dpi=150)
    for ax, (fld, lab, cm) in zip(
            axes, [(p1.reshape(side, side), r"$\phi_1$ (polymer)", "Blues"),
                   (p2.reshape(side, side), r"$\phi_2$ (fullerene)",
                    "Oranges")]):
        im = ax.imshow(fld, origin="lower", cmap=cm, vmin=0, vmax=0.9)
        ax.set_title(lab, fontsize=11); ax.set_xticks([]); ax.set_yticks([])
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle("Final ternary morphology (the two solute fields)",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    c = r["chi"]
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PfourChiab", f"{c[0]:g}"),
             mac("PfourChias", f"{c[1]:g}"),
             mac("PfourChibs", f"{c[2]:g}"),
             mac("PfourPhione", f"{r['phi0'][0]:.2f}"),
             mac("PfourPhitwo", f"{r['phi0'][1]:.2f}"),
             mac("PfourSpreadStart", f"{r['spread0']:.4f}"),
             mac("PfourSpreadEnd", f"{r['spreadf']:.4f}"),
             mac("PfourPhaseA",
                 f"$({r['phaseA'][0]:.3f},\\,{r['phaseA'][1]:.3f})$"),
             mac("PfourPhaseB",
                 f"$({r['phaseB'][0]:.3f},\\,{r['phaseB'][1]:.3f})$"),
             mac("PfourDrift",
                 f"{max(r['mass1_drift'], r['mass2_drift']):.1e}"
                 .replace("e-0", r"\times10^{-").replace("e+0", r"\times10^{")
                 + "}")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    ap.add_argument("--t_end", type=float, default=0.6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    r = run(dm, mesh, cons, t_end=args.t_end, device=args.device)
    fig_gibbs(r, "p4_gibbs.png")
    fig_fields(r, "p4_fields.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
