"""OrgElMorph course - Differentiable D4: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and numbers into
../../latex/numbers/d4.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from schedule import schedule_gradient

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d4.tex")


def _sci(val, digits=3):
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    names = ["DfourGradTa", "DfourGradTb", "DfourGradTc", "DfourGradTd"]
    lines = [
        "% AUTO-GENERATED by differentiable/04 gen_figures.py - do not edit.",
        mac("DfourSteps", f"{r['NS']}"),
        mac("DfourJ", _sci(r["J"])),
        mac("DfourRelFD", _sci(r["rel"].max(), 1)),
        mac("DfourPsiTgt", f"{r['tgt_psi']:g}"),
    ]
    for nm, g in zip(names, r["gT_adj"]):
        lines.append(mac(nm, _sci(g)))
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def process_figure(r, fname):
    """Left: the imposed schedule T(t) and the crystallinity <psi> it
    produces. Right: the schedule gradient dJ/dT_n (adjoint bars, FD
    dots) - one number per step, from a single reverse sweep."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.2), dpi=150)
    steps = np.arange(r["NS"])

    ax1.plot(steps, r["Tsched"], "s-", color="C1", lw=1.8,
             label="temperature $T_n$")
    ax1.set_xlabel("process step $n$")
    ax1.set_ylabel("temperature $T_n$", color="C1")
    ax1.tick_params(axis="y", labelcolor="C1")
    axb = ax1.twinx()
    axb.plot(steps, r["cryst"], "o-", color="C2", lw=1.8,
             label=r"crystallinity $\langle\psi\rangle$")
    axb.set_ylabel(r"crystallinity $\langle\psi\rangle$", color="C2")
    axb.tick_params(axis="y", labelcolor="C2")
    ax1.set_title("The process: schedule in, crystallinity out")
    ax1.set_xticks(steps)

    ax2.bar(steps, r["gT_adj"], 0.55, color="C0", label="adjoint")
    ax2.plot(steps, r["gT_fd"], "D", color="C3", ms=8,
             label="finite diff")
    ax2.axhline(0, color="k", lw=0.8)
    ax2.set_xlabel("process step $n$")
    ax2.set_ylabel(r"$dJ/dT_n$")
    ax2.set_title("Schedule gradient (one sweep, all steps)")
    ax2.set_xticks(steps)
    ax2.legend()
    ax2.grid(axis="y", alpha=0.3)

    fig.suptitle("Process gradients: differentiating the quench schedule "
                 "$T(t)$", fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = schedule_gradient(level=args.level, device=args.device)
    process_figure(r, "d4_schedule.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
