"""OrgElMorph course - Differentiable D3: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and numbers into
../../latex/numbers/d3.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from recover import recover

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d3.tex")


def _sci(val, digits=2):
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    ct, kt = r["truth"]
    cr, kr = r["recovered"]
    lines = [
        "% AUTO-GENERATED by differentiable/03 gen_figures.py - do not edit.",
        mac("DthreeSteps", f"{r['n_steps']}"),
        mac("DthreeIter", f"{r['n_iter']}"),
        mac("DthreeChiTruth", f"{ct:g}"),
        mac("DthreeChiRec", f"{cr:.5f}"),
        mac("DthreeKappaTruth", f"{kt:g}"),
        mac("DthreeKappaRec", f"{kr:.5f}"),
        mac("DthreeErrChi", _sci(r["err_chi"], 1)),
        mac("DthreeErrKappa", _sci(r["err_kappa"], 1)),
        mac("DthreeLossStart", _sci(r["loss0"], 2)),
        mac("DthreeLossEnd", _sci(r["loss_end"], 1)),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def descent_figure(r, fname):
    """Left: the field misfit loss falling to the solver floor. Right: the
    optimiser's path in (chi, kappa) space, from the wrong guess to the
    ground truth (star)."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.2), dpi=150)

    it = np.arange(r["loss_hist"].size)
    ax1.semilogy(it, r["loss_hist"], "o-", color="C0", lw=1.6)
    ax1.set_xlabel("optimiser evaluation")
    ax1.set_ylabel(r"field misfit $L=\frac{1}{2}|c_N-c_N^{\mathrm{target}}|^2$")
    ax1.set_title("Loss collapses to the solver floor")
    ax1.grid(which="both", alpha=0.3)

    ct, kt = r["truth"]
    ax2.plot(r["chi_hist"], r["kappa_hist"], "o-", color="C3", lw=1.6,
             label="optimiser path")
    ax2.plot(r["chi_hist"][0], r["kappa_hist"][0], "s", color="C1",
             ms=11, label="initial guess")
    ax2.plot(ct, kt, "*", color="k", ms=18, label="ground truth")
    ax2.set_xlabel(r"interaction $\chi$")
    ax2.set_ylabel(r"gradient penalty $\kappa$")
    ax2.set_title(r"Parameters converge: $(\chi,\kappa)\to$ truth")
    ax2.legend()
    ax2.grid(alpha=0.3)

    fig.suptitle("Recovering material parameters from a morphology",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    ap.add_argument("--steps", type=int, default=6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = recover(level=args.level, n_steps=args.steps, device=args.device)
    descent_figure(r, "d3_descent.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
