"""OrgElMorph course - Differentiable D3: recover parameters from a morphology.

Importable core for the third differentiable concept - the first true
INVERSE problem.  Given a target morphology (here generated by a known
"ground-truth" material), recover the material parameters that produced
it by gradient descent: minimise the field misfit

    L(theta) = 1/2 || c_N(theta) - c_N^target ||^2 ,   theta = (chi, kappa),

using the adjoint gradient dL/dtheta and a quasi-Newton optimiser
(L-BFGS-B).  This is the tutorial-scale version of "learn the material
from the morphology": the same loop that, at research scale, fits a
free-energy functional to experimental micrographs (Wodo-Ganapathysubramanian).

Because the adjoint returns dL/dchi and dL/dkappa exactly and cheaply,
each optimiser step is one forward rollout + one reverse sweep, and the
loss falls to the solver floor while (chi, kappa) -> truth.  We use a
short, interior Flory-Huggins rollout so the logs stay smooth.
"""
import numpy as np
from scipy.optimize import minimize

from diffsim.octree.build import build_uniform
from diffsim.mesh.nodes import build_mesh
from diffsim.mesh.constraints import build_constraints
from diffsim.mesh.basis import basis_tables
from diffsim.assembly.operators import DeviceMesh
from diffsim.adjoint.phasefield import CHForward, CHAdjoint, FHEnergy


def build_dm(level=3, device="cuda:0"):
    tree = build_uniform(level, dim=2)
    mesh = build_mesh(tree, p=1)
    cons = build_constraints(mesh)
    dm = DeviceMesh.from_mesh(mesh, cons, basis_tables(1, dim=2), device)
    return dm, mesh


def _ic(coords):
    return 0.5 + 0.1 * np.cos(np.pi * coords[:, 0]) \
        * np.cos(np.pi * coords[:, 1])


def _march(dm, coords, chi, kappa, n_steps, dt, M, A, order):
    fwd = CHForward(dm, FHEnergy(A, chi), M=M, kappa=kappa, dt=dt,
                    order=order)
    fwd.set_initial(_ic(coords))
    fwd.run(n_steps)
    return fwd, fwd.steps[-1]["c"]


def loss_and_grad(dm, coords, theta, target, n_steps, dt, M, A, order):
    """L = 1/2 ||c_N - target||^2 and its adjoint gradient dL/d(chi,kappa).
    One forward rollout + one reverse sweep."""
    chi, kappa = float(theta[0]), float(theta[1])
    nn = dm.n_nodes
    fwd, cN = _march(dm, coords, chi, kappa, n_steps, dt, M, A, order)
    r = cN - target
    L = 0.5 * float(r @ r)
    dJdx = [np.zeros(2 * nn) for _ in range(n_steps)]
    dJdx[-1][0::2] = r                       # dL/dc_N seeds the sweep
    g = CHAdjoint(fwd).gradient(dJdx, ["B", "kappa"])
    return L, np.array([g["B"], g["kappa"]])


def make_target(dm, coords, chi_true, kappa_true, n_steps, dt, M, A,
                order):
    _, cN = _march(dm, coords, chi_true, kappa_true, n_steps, dt, M, A,
                   order)
    return cN.copy()


def recover(level=3, n_steps=6, dt=0.005, M=1.0, A=1.0, order=1,
            chi_true=2.5, kappa_true=0.01, chi0=2.1, kappa0=0.02,
            bounds=((1.8, 2.8), (5e-3, 3e-2)), device="cuda:0"):
    """Generate a target from (chi_true, kappa_true), then recover it from
    the initial guess (chi0, kappa0) by L-BFGS-B on the adjoint gradient.
    Returns the loss/parameter trajectories and the recovered values."""
    dm, mesh = build_dm(level, device)
    coords = mesh.node_coords
    target = make_target(dm, coords, chi_true, kappa_true, n_steps, dt, M,
                         A, order)

    hist = dict(loss=[], chi=[], kappa=[])

    def fg(theta):
        L, g = loss_and_grad(dm, coords, theta, target, n_steps, dt, M, A,
                             order)
        return L, g

    def cb(theta):
        L, _ = fg(theta)
        hist["loss"].append(L)
        hist["chi"].append(float(theta[0]))
        hist["kappa"].append(float(theta[1]))

    theta0 = np.array([chi0, kappa0])
    L0, _ = fg(theta0)
    hist["loss"].append(L0)
    hist["chi"].append(chi0)
    hist["kappa"].append(kappa0)
    res = minimize(fg, theta0, jac=True, method="L-BFGS-B",
                   bounds=bounds, callback=cb,
                   options=dict(maxiter=100, ftol=1e-16, gtol=1e-12))

    chi_rec, kappa_rec = float(res.x[0]), float(res.x[1])
    return dict(
        truth=(chi_true, kappa_true), guess=(chi0, kappa0),
        recovered=(chi_rec, kappa_rec),
        err_chi=abs(chi_rec - chi_true), err_kappa=abs(kappa_rec - kappa_true),
        loss0=float(L0), loss_end=float(res.fun),
        loss_hist=np.asarray(hist["loss"]),
        chi_hist=np.asarray(hist["chi"]),
        kappa_hist=np.asarray(hist["kappa"]),
        n_iter=len(hist["loss"]), n_steps=n_steps,
        side=int(round(np.sqrt(dm.n_nodes))))


def fd_check(level=3, n_steps=6, dt=0.005, M=1.0, A=1.0, order=1,
             chi_true=2.5, kappa_true=0.01, theta=(2.1, 0.015),
             device="cuda:0"):
    """FD-verify the fitting-loss gradient at an off-truth point (the
    self-check the optimiser relies on).  Returns (adj, fd, rel) per
    parameter."""
    dm, mesh = build_dm(level, device)
    coords = mesh.node_coords
    target = make_target(dm, coords, chi_true, kappa_true, n_steps, dt, M,
                         A, order)
    theta = np.asarray(theta, float)
    _, g_adj = loss_and_grad(dm, coords, theta, target, n_steps, dt, M, A,
                             order)
    g_fd = np.zeros(2)
    for i in range(2):
        e = 1e-6 * max(1.0, abs(theta[i]))
        hi = theta.copy(); hi[i] += e
        lo = theta.copy(); lo[i] -= e
        Lh, _ = loss_and_grad(dm, coords, hi, target, n_steps, dt, M, A,
                              order)
        Ll, _ = loss_and_grad(dm, coords, lo, target, n_steps, dt, M, A,
                              order)
        g_fd[i] = (Lh - Ll) / (2 * e)
    rel = np.abs(g_adj - g_fd) / np.maximum(np.abs(g_fd), 1e-14)
    return g_adj, g_fd, rel
