"""OrgElMorph course - Computational C5: figures + numbers.

Writes the dof-growth figure and the nnz-vs-dofs figure (with the int32
ceiling and cited device-scale points) into ../../latex/figures/, and the
measured macros into ../../latex/numbers/c5.tex.  Live 2-D/tiny-3-D;
cited device-scale points from the dev notes.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from scaling import measure_scaling, CITED_LADDER, INT32_MAX

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "c5.tex")


def dof_growth_figure(s, fname):
    fig, ax = plt.subplots(figsize=(6.4, 4.5), dpi=150)
    for recs, col, lab in ((s["two_d"], "C0", "2-D ($\\times4$/level)"),
                           (s["three_d"], "C3",
                            "3-D ($\\times8$/level)")):
        lv = [r["level"] for r in recs]
        dofs = [r["dofs"] for r in recs]
        ax.semilogy(lv, dofs, "o-", color=col, lw=2, ms=8, label=lab)
    ax.set_xlabel("refinement level")
    ax.set_ylabel("degrees of freedom")
    ax.set_title("Degrees of freedom explode faster in 3-D")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def nnz_figure(s, fname):
    fig, ax = plt.subplots(figsize=(6.8, 4.7), dpi=150)
    for recs, col, lab in ((s["two_d"], "C0", "2-D live"),
                           (s["three_d"], "C3", "3-D live")):
        d = [r["dofs"] for r in recs]
        n = [r["nnz"] for r in recs]
        ax.loglog(d, n, "o-", color=col, lw=2, ms=8, label=lab)
    # cited device-scale points
    cd = [c[1] for c in CITED_LADDER]
    cn = [c[2] for c in CITED_LADDER]
    ax.loglog(cd, cn, "D", color="C1", ms=9, label="cited (dev notes)")
    for (label, dofs, nnz, note) in CITED_LADDER:
        ax.annotate(label.split(" ")[0], (dofs, nnz), fontsize=7,
                    xytext=(4, -8), textcoords="offset points")
    ax.axhline(INT32_MAX, ls="--", color="k", alpha=0.6)
    ax.text(ax.get_xlim()[0] * 1.2, INT32_MAX * 1.3,
            "int32 nnz ceiling ($2^{31}$)", fontsize=8)
    ax.set_xlabel("degrees of freedom")
    ax.set_ylabel("matrix nonzeros (nnz)")
    ax.set_title("Matrix nonzeros vs.\\ problem size (live + cited)")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend(loc="lower right")
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(s):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    a = s["two_d"][-1]      # 2-D L7
    b = s["three_d"][-1]    # 3-D L5
    lines = [
        "% AUTO-GENERATED by gen_figures.py - do not edit.",
        mac("CfiveDofGrowthTwoD", f"{s['dof_growth_2d']:.1f}"),
        mac("CfiveDofGrowthThreeD", f"{s['dof_growth_3d']:.1f}"),
        mac("CfiveNnzPerDofTwoD", f"{s['nnz_per_dof_2d']:.0f}"),
        mac("CfiveNnzPerDofThreeD", f"{s['nnz_per_dof_3d']:.0f}"),
        mac("CfiveTwoDdofs", f"{a['dofs']:,}".replace(",", r"{,}")),
        mac("CfiveThreeDdofs", f"{b['dofs']:,}".replace(",", r"{,}")),
        mac("CfiveNnzRatio", f"{b['nnz'] / a['nnz']:.1f}"),
        mac("CfiveStepRatio", f"{b['step_s'] / a['step_s']:.1f}"),
        # cited anchors
        mac("CfiveFilmDofs", f"{CITED_LADDER[1][1]:,}".replace(",", r"{,}")),
        mac("CfiveMkOverflowDofs",
            f"{CITED_LADDER[2][1]:,}".replace(",", r"{,}")),
        mac("CfiveNovaDofs", f"{CITED_LADDER[3][1]:,}"
            .replace(",", r"{,}")),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    s = measure_scaling(device=args.device)
    dof_growth_figure(s, "c5_dofgrowth.png")
    nnz_figure(s, "c5_nnz.png")
    write_numbers(s)


if __name__ == "__main__":
    main()
