"""OrgElMorph course - Physics P1: render the figures the LaTeX shows.

Writes into ../../latex/figures/ (the swappable-image convention: the
LaTeX \\includegraphics these by name; re-running regenerates them).
Uses the SAME core as run.py, so the document's figures and the
student's own run come from identical physics.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from spinodal import run_spinodal
from run import summarize

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "p1.tex")


def write_numbers(recs):
    """Emit latex/numbers.tex so the document's cited numbers ARE the
    measured output of this run (no hand-copied values)."""
    s = {r["energy"]: summarize(r) for r in recs}
    p, f = s["poly"], s["fh"]

    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    def crange(d):
        return f"$[{d['c_min']:.2f},\\,{d['c_max']:.2f}]$"

    def mass(d):
        if d["mass_drift"] < 1e-14:      # machine zero
            return r"$<10^{-14}$ (machine)"
        m, e = f"{d['mass_drift']:.1e}".split("e")
        return f"${m}\\times10^{{{int(e)}}}$"

    fh_rec = next(r for r in recs if r["energy"] == "fh")
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("FHA", f"{fh_rec['params']['fh_A']:g}"),
             mac("FHB", f"{fh_rec['params']['fh_B']:g}")]
    for pre, d in (("POLY", p), ("FH", f)):
        lines += [
            mac(f"{pre}Fstart", f"{d['F0']:.3g}"),
            mac(f"{pre}Fend", f"{d['Fend']:.3g}"),
            mac(f"{pre}Fintpeak", f"{d['Fint_peak']:.3g}"),
            mac(f"{pre}Fintend", f"{d['Fint_end']:.3g}"),
            mac(f"{pre}crange", crange(d)),
            mac(f"{pre}mass", mass(d)),
        ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def morphology_strip(rec, fname, cmap):
    ns = sorted(rec["snaps"])
    fig, axes = plt.subplots(1, len(ns), figsize=(3.1 * len(ns), 3.2),
                             dpi=150)
    for ax, n in zip(axes, ns):
        im = ax.imshow(rec["snaps"][n], origin="lower", cmap=cmap,
                       vmin=rec["snaps"][ns[-1]].min(),
                       vmax=rec["snaps"][ns[-1]].max())
        ax.set_title(f"step {n}  (t = {rec['t'][n]:.2f})", fontsize=11)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02, label="c")
    fig.suptitle(f"Spinodal decomposition - {rec['energy'].upper()} "
                 f"free energy", fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def energy_curves(recs, fname):
    fig, axes = plt.subplots(1, len(recs), figsize=(6.2 * len(recs), 4.0),
                             dpi=150, squeeze=False)
    for ax, rec in zip(axes[0], recs):
        t = rec["t"]
        ax.plot(t, rec["F_total"], "k-", lw=2, label="total $F$")
        ax.plot(t, rec["F_bulk"], "C0--", lw=1.5, label="bulk")
        ax.plot(t, rec["F_interface"], "C3-.", lw=1.5,
                label="interfacial")
        ax.set_xlabel("time $t$"); ax.set_ylabel("free energy")
        ax.set_title(f"{rec['energy'].upper()} free energy")
        ax.legend(); ax.grid(alpha=0.3)
    fig.suptitle("Ginzburg-Landau energy decay (Lyapunov functional)",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    ap.add_argument("--steps", type=int, default=250)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    snaps = [0, args.steps // 20, args.steps // 4, args.steps]
    recs = []
    for e, cmap in (("poly", "RdBu_r"), ("fh", "viridis")):
        rec = run_spinodal(energy=e, level=args.level, steps=args.steps,
                           device=args.device, snap_steps=snaps)
        morphology_strip(rec, f"p1_morph_{e}.png", cmap)
        recs.append(rec)
    energy_curves(recs, "p1_energy.png")
    write_numbers(recs)


if __name__ == "__main__":
    main()
