"""OrgElMorph course - Physics P1 driver (the file the student runs).

    python run.py                # both energies, default 128x128
    python run.py --energy fh    # just Flory-Huggins
    python run.py --level 6      # 64x64 (faster)

Prints the energy budget as it marches and writes a self-check table
(compare against EXPECTED.md) plus snapshot + energy-curve PNGs into
./out/.  The figures in the LaTeX are generated by gen_figures.py from
this same core (spinodal.py)."""
import argparse
import os

import numpy as np

from spinodal import run_spinodal


def summarize(rec):
    """The numbers the LaTeX cites and EXPECTED.md self-checks."""
    F = rec["F_total"]
    drift = abs(rec["mass"][-1] - rec["mass"][0])
    # monotone decrease after the step-0 mu-consistency transient
    mono = bool(np.all(np.diff(F[1:]) <= 1e-9))
    return dict(
        energy=rec["energy"],
        F0=float(F[0]), F1=float(F[1]), Fend=float(F[-1]),
        Fbulk_end=float(rec["F_bulk"][-1]),
        # interfacial energy is always >= 0 (a gradient penalty); report
        # it directly.  Its DECAY during coarsening is the length-scale
        # story.  (A "fraction of total" is sign-ambiguous for FH, whose
        # total energy is entropy-dominated and can be negative.)
        Fint_end=float(rec["F_interface"][-1]),
        Fint_peak=float(np.max(rec["F_interface"])),
        c_min=float(rec["snaps"][max(rec["snaps"])].min()),
        c_max=float(rec["snaps"][max(rec["snaps"])].max()),
        mass_drift=drift, monotone_after_step1=mono)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--energy", choices=["poly", "fh", "both"],
                    default="both")
    ap.add_argument("--level", type=int, default=6)
    ap.add_argument("--steps", type=int, default=250)
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()
    os.makedirs("out", exist_ok=True)

    which = ["poly", "fh"] if args.energy == "both" else [args.energy]
    for e in which:
        rec = run_spinodal(energy=e, level=args.level, steps=args.steps,
                           device=args.device)
        s = summarize(rec)
        print(f"\n=== {e.upper()} free energy "
              f"({rec['side']}x{rec['side']}, {args.steps} steps) ===")
        print(f"  F: {s['F0']:.5g} (step0) -> {s['F1']:.5g} (step1) "
              f"-> {s['Fend']:.5g} (end)")
        print(f"  end split: bulk {s['Fbulk_end']:.5g} + interface "
              f"{s['Fint_end']:.5g}  (interfacial energy peaks at "
              f"{s['Fint_peak']:.5g} then decays as domains coarsen)")
        print(f"  phases: c in [{s['c_min']:.3f}, {s['c_max']:.3f}]")
        print(f"  mass drift |dm| = {s['mass_drift']:.2e}  "
              f"(conserved)")
        print(f"  energy monotone decreasing after step 1: "
              f"{s['monotone_after_step1']}")
        np.savez(f"out/p1_{e}.npz", **{k: rec[k] for k in
                 ("t", "F_total", "F_bulk", "F_interface", "mass")},
                 **{f"snap_{n}": rec["snaps"][n] for n in rec["snaps"]})
    print("\nField/energy arrays written to out/.  Compare the printed "
          "table with EXPECTED.md; render figures with gen_figures.py.")


if __name__ == "__main__":
    main()
