"""OrgElMorph course - Physics P2: render figures + number macros.

EVERYTHING here is rendered purely from a SAVED run directory
(``results.json`` + ``history.npz`` produced by ``run_harness.py``) -- no
physics is re-run, so the document's figures and cited numbers ARE the measured
output of the reference run.

    PYTHONPATH=<repo>/src python run_harness.py --config configs/p2.yaml \\
        --mode reference --output outputs/p2 --overwrite
    python gen_figures.py --run outputs/p2

Writes ``../../latex/figures/p2_*.png`` and ``../../latex/numbers/p2.tex``.
"""
import argparse
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = os.path.dirname(__file__)
FIGDIR = os.path.join(HERE, "..", "..", "latex", "figures")
NUMTEX = os.path.join(HERE, "..", "..", "latex", "numbers", "p2.tex")


# --------------------------------------------------------------------------
# number macros (all \ensuremath-wrapped; NO bare $ or \times in macro bodies)
# --------------------------------------------------------------------------
def _sci(x, sig=1):
    s = f"{x:.{sig}e}"
    m, e = s.split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def _num(x):
    return rf"\ensuremath{{{x}}}"


def write_numbers(R):
    ref, fx, ad = R["reference"], R["fixed"], R["adaptive"]
    mt, kn, wc = R["matched"], R["knee"], R["worst_case"]
    o = R["order"]
    # "safe fixed" = the headline representative fixed step (the one shown in
    # the morphology/energy figures); "cliff" = the smallest fixed step that
    # fails to resolve the quench (relL2 >= 0.1).
    safe = fx
    fail = [f for f in R["fixed_sweep"] if f["relL2"] >= 0.1]
    cliff = min(fail, key=lambda f: f["dt"]) if fail else None

    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    L = ["% AUTO-GENERATED by gen_figures.py from results.json - do not edit.",
         mac("PtwoSide", _num(R["mesh"]["side"])),
         mac("PtwoKappa", _sci(R["mesh"]["kappa"])),
         mac("PtwoTend", _num(f'{R["mesh"]["t_end"]:g}')),
         mac("PtwoOrderBDFone", _num(f'{o["bdf1"]["observed_order"]:.2f}')),
         mac("PtwoOrderBDFtwo", _num(f'{o["bdf2"]["observed_order"]:.2f}')),
         mac("PtwoRefdt", _sci(ref["dt"])),
         mac("PtwoRefsteps", _num(f'{ref["nsteps"]:,}'.replace(",", r"\,"))),
         mac("PtwoRefF", _num(f'{ref["F"]:.4g}')),
         mac("PtwoReflam", _num(f'{ref["lam1"]:.1f}')),
         mac("PtwoRefselfcheck", _sci(ref["selfcheck_relL2"])),
         mac("PtwoSafedt", _sci(safe["dt"])),
         mac("PtwoSafesteps", _num(safe["nsteps"])),
         mac("PtwoSaferelL", _sci(safe["relL2"])),
         mac("PtwoFixedOrder", _num(f'{R["fixed_order"]:.2f}')),
         mac("PtwoTol", _sci(ad["tol"])),
         mac("PtwoAccepted", _num(ad["accepted"])),
         mac("PtwoRejected", _num(ad["rejected"])),
         mac("PtwoFull", _num(ad["full_solves"])),
         mac("PtwoHalf", _num(ad["half_solves"])),
         mac("PtwoNewton", _num(f'{ad["newton"]:,}'.replace(",", r"\,"))),
         mac("PtwoWall", _num(f'{ad["wall_s"]:.1f}')),
         mac("PtwoDtmin", _sci(ad["dt_min"])),
         mac("PtwoDtmax", _sci(ad["dt_max"])),
         mac("PtwoAdrelL", _sci(ad["relL2"])),
         mac("PtwoAdFerr", _sci(ad["err_energy"])),
         mac("PtwoAdlamErr", _num(f'{100 * ad["err_lam1"]:.2f}')),
         mac("PtwoAdlam", _num(f'{ad["lam1"]:.1f}')),
         mac("PtwoMatchedSolves",
             _num(f'{mt["matched_fixed_solves"]:,}'.replace(",", r"\,"))),
         mac("PtwoMatchedSteps",
             _num(f'{mt["matched_fixed_steps"]:,}'.replace(",", r"\,"))),
         mac("PtwoSpeedupSolves", _num(f'{mt["speedup_solves"]:.1f}')),
         mac("PtwoSpeedupSteps", _num(f'{mt["speedup_steps"]:.1f}')),
         mac("PtwoWorstImplied",
             _num(f'{wc["implied_steps"]:,}'.replace(",", r"\,"))),
         mac("PtwoKneeTol", _sci(kn["tol"])),
         mac("PtwoNtols", _num(len(R["adaptive_sweep"]))),
         ]
    if cliff is not None:
        L += [mac("PtwoCliffdt", _sci(cliff["dt"])),
              mac("PtwoCliffrelL", _num(f'{cliff["relL2"]:.2g}'))]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(L) + "\n")
    print("wrote", NUMTEX)


# --------------------------------------------------------------------------
# figures
# --------------------------------------------------------------------------
def fig_order(R, H, fname):
    o = R["order"]
    dts = H["order_dts"]
    fig, ax = plt.subplots(figsize=(6.0, 4.6), dpi=150)
    for tag, err, c, mk in (("BDF1", H["order_bdf1_err"], "C0", "o"),
                            ("BDF2", H["order_bdf2_err"], "C3", "s")):
        p = o[tag.lower()]["observed_order"]
        ax.loglog(dts, err, c + "-" + mk, lw=1.8, ms=7,
                  label=f"{tag}  (observed order {p:.2f})")
    d = np.array(dts, dtype=float)
    ax.loglog(d, H["order_bdf1_err"][0] * (d / d[0]) ** 1, "C0:", lw=1,
              alpha=0.6, label="slope 1")
    ax.loglog(d, H["order_bdf2_err"][0] * (d / d[0]) ** 2, "C3:", lw=1,
              alpha=0.6, label="slope 2")
    ax.set_xlabel(r"time step $\Delta t$")
    ax.set_ylabel(r"relative $L_2$ error at $T$")
    ax.set_title("Temporal order: smooth single-mode relaxation")
    ax.legend(fontsize=9); ax.grid(alpha=0.3, which="both")
    _save(fig, fname)


def fig_convergence(R, H, fname):
    fig, (a0, a1) = plt.subplots(1, 2, figsize=(12.2, 4.6), dpi=150)
    tols = H["sweep_tols"]
    rel = H["sweep_relL2"]
    Ferr = H["sweep_err_energy"]
    a0.loglog(tols, rel, "C0-o", lw=1.8, ms=6,
              label=r"relative $L_2$ of $c(T)$")
    a0.loglog(tols, Ferr, "C2-s", lw=1.5, ms=6,
              label=r"free-energy error $|\Delta F|$")
    kt = R["knee"]["tol"]
    a0.axvline(kt, color="k", ls="--", lw=1, alpha=0.6)
    a0.set_xlabel("controller tolerance"); a0.set_ylabel("error vs reference")
    a0.set_title("Error vs tolerance (knee = diminishing returns)")
    a0.legend(fontsize=9); a0.grid(alpha=0.3, which="both")
    a1.loglog(H["sweep_wall"], rel, "C0-o", lw=1.8, ms=6,
              label="adaptive (tol sweep)")
    conv = H["fixed_relL2"] < 0.1
    a1.loglog(H["fixed_wall"][conv], H["fixed_relL2"][conv], "C3-s", lw=1.8,
              ms=6, label="fixed dt (convergent)")
    a1.set_xlabel("wall time (s)")
    a1.set_ylabel(r"relative $L_2$ of $c(T)$")
    a1.set_title("Cost vs accuracy")
    a1.legend(fontsize=9); a1.grid(alpha=0.3, which="both")
    _save(fig, fname)


def fig_dt_newton(R, H, fname):
    fig, (a0, a1) = plt.subplots(2, 1, figsize=(8.6, 6.4), dpi=150, sharex=True)
    t = H["ad_acc_t"]; dt = H["ad_acc_dt"]; nw = H["ad_acc_newton"]
    a0.semilogy(t, dt, "C0-", lw=1.4)
    a0.axhline(R["fixed"]["dt"], color="C3", ls="--", lw=1.3,
               label=f'safe fixed $\\Delta t={R["fixed"]["dt"]:g}$')
    a0.axhline(R["reference"]["dt"], color="0.5", ls=":", lw=1.2,
               label=f'reference $\\Delta t={R["reference"]["dt"]:g}$')
    a0.set_ylabel(r"accepted $\Delta t$")
    a0.set_title("Adaptive step collapses through the quench, "
                 "grows through coarsening")
    a0.legend(fontsize=9, loc="lower right"); a0.grid(alpha=0.3, which="both")
    a1.plot(t, nw, "C2-", lw=1.2)
    a1.set_xlabel("time $t$")
    a1.set_ylabel("Newton solves\nper accepted step")
    a1.set_title("Solver work per step (full + two half solves)")
    a1.grid(alpha=0.3)
    _save(fig, fname)


def fig_morphology(R, H, fname):
    flds = [(f'reference $\\Delta t={R["reference"]["dt"]:g}$\n'
             f'{R["reference"]["nsteps"]} steps', H["field_ref"]),
            (f'safe fixed $\\Delta t={R["fixed"]["dt"]:g}$\n'
             f'{R["fixed"]["nsteps"]} steps', H["field_fixed"]),
            (f'adaptive tol$={R["adaptive"]["tol"]:g}$\n'
             f'{R["adaptive"]["accepted"]} accepted steps', H["field_adapt"])]
    fig, axes = plt.subplots(1, 3, figsize=(11.4, 4.1), dpi=150)
    for ax, (title, fld) in zip(axes, flds):
        im = ax.imshow(fld.T, origin="lower", cmap="RdBu_r", vmin=-1.05,
                       vmax=1.05)
        ax.set_title(title, fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02, label="c")
    fig.suptitle("Coarsened morphology: robust statistics (energy, domain "
                 "scale) agree;\nthe exact pattern is step-sequence sensitive, "
                 "as it is seed sensitive", fontsize=10, y=1.06)
    _save(fig, fname)


def fig_energy(R, H, fname):
    fig, ax = plt.subplots(figsize=(6.4, 4.4), dpi=150)
    ax.plot(H["ref_energy_t"], H["ref_energy_F"], "0.5", lw=2.4,
            label=f'reference ({R["reference"]["nsteps"]} steps)')
    ax.plot(H["fx_energy_t"], H["fx_energy_F"], "C3--", lw=1.6,
            label=f'safe fixed ({R["fixed"]["nsteps"]} steps)')
    ax.plot(H["ad_energy_t"], H["ad_energy_F"], "C0-", lw=1.4,
            label=f'adaptive ({R["adaptive"]["accepted"]} steps)')
    ax.set_xlabel("time $t$"); ax.set_ylabel("free energy $F$")
    ax.set_title("Same energy trajectory, far fewer adaptive steps")
    ax.legend(fontsize=9); ax.grid(alpha=0.3)
    _save(fig, fname)


def _save(fig, fname):
    os.makedirs(FIGDIR, exist_ok=True)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default=os.path.join(HERE, "outputs", "p2"),
                    help="saved run directory (results.json + history.npz)")
    args = ap.parse_args()
    with open(os.path.join(args.run, "results.json")) as fh:
        R = json.load(fh)
    H = dict(np.load(os.path.join(args.run, "history.npz")))
    fig_order(R, H, "p2_order.png")
    fig_convergence(R, H, "p2_convergence.png")
    fig_dt_newton(R, H, "p2_dt_newton.png")
    fig_morphology(R, H, "p2_morphology.png")
    fig_energy(R, H, "p2_energy.png")
    write_numbers(R)


if __name__ == "__main__":
    main()
