"""OrgElMorph course - Physics P2: render the figures + numbers macros.

Writes ../../latex/figures/p2_*.png and ../../latex/numbers/p2.tex from
the SAME core the student runs (adaptive.py), so the document's figures
and numbers ARE the measured output.

    python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from adaptive import build_mesh_dm, compare

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p2.tex")


def _sci(x):
    """Render a float as LaTeX a\\times10^{b}."""
    s = f"{x:.1e}"
    m, e = s.split("e")
    return rf"{m}\times10^{{{int(e)}}}"


def write_numbers(r):
    fx, ad = r["fixed"], r["adaptive"]

    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PtwoTend", f"{r['t_end']:g}"),
             mac("PtwoDtfixed", f"{r['dt_fixed']:g}"),
             mac("PtwoTol", f"{r['tol']:g}"),
             mac("PtwoNfixed", f"{fx['nsteps']}"),
             mac("PtwoNadapt", f"{ad['nsteps']}"),
             mac("PtwoSpeedup", f"{r['speedup']:.1f}"),
             mac("PtwoDtmin", f"${_sci(r['dt_min'])}$"),
             mac("PtwoDtmax", f"{ad['dt_hist'].max():.3f}"),
             mac("PtwoImplied", f"{r['implied_fixed']:,}".replace(",", r"\,")),
             mac("PtwoFfixed", f"{fx['F'][-1]:.4g}"),
             mac("PtwoFadapt", f"{ad['F'][-1]:.4g}"),
             mac("PtwodF", f"${_sci(r['dF_end'])}$"),
             mac("PtwoDscaleFixed", f"{r['dscale_fixed']:.1f}"),
             mac("PtwoDscaleAdapt", f"{r['dscale_adapt']:.1f}"),
             mac("PtwoCrange",
                 f"$[{r['crange_adapt'][0]:.2f},\\,"
                 f"{r['crange_adapt'][1]:.2f}]$")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def fig_dt_and_energy(r, fname):
    fx, ad = r["fixed"], r["adaptive"]
    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12.4, 4.2), dpi=150)
    # (a) dt history: adaptive dt climbs as coarsening slows
    ax0.step(np.cumsum(ad["dt_hist"]), ad["dt_hist"], "C0-", where="post",
             lw=1.6, label="adaptive dt")
    ax0.axhline(r["dt_fixed"], color="C3", ls="--", lw=1.5,
                label=f"fixed dt = {r['dt_fixed']:g}")
    ax0.set_yscale("log")
    ax0.set_xlabel("time $t$"); ax0.set_ylabel("time step $dt$")
    ax0.set_title("Adaptive step size grows through coarsening")
    ax0.legend(); ax0.grid(alpha=0.3, which="both")
    # (b) energy decay: the two integrators agree
    ax1.plot(fx["t"], fx["F"], "C3--", lw=2,
             label=f"fixed ({fx['nsteps']} steps)")
    ax1.plot(ad["t"], ad["F"], "C0-", lw=1.6,
             label=f"adaptive ({ad['nsteps']} steps)")
    ax1.set_xlabel("time $t$"); ax1.set_ylabel("free energy $F$")
    ax1.set_title("Same energy trajectory, far fewer steps")
    ax1.legend(); ax1.grid(alpha=0.3)
    fig.suptitle("LTE-controlled adaptive time stepping "
                 "(binary Cahn--Hilliard quench)", fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_morph(r, fname):
    fx, ad = r["fixed"], r["adaptive"]
    fig, axes = plt.subplots(1, 2, figsize=(8.4, 4.1), dpi=150)
    for ax, (title, fld) in zip(
            axes, [(f"naive fixed dt ({fx['nsteps']} steps)", fx["field"]),
                   (f"adaptive ({ad['nsteps']} steps)", ad["field"])]):
        im = ax.imshow(fld.T, origin="lower", cmap="RdBu_r",
                       vmin=-1.05, vmax=1.05)
        ax.set_title(title, fontsize=11)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, fraction=0.03, pad=0.02, label="c")
    fig.suptitle("Coarsened morphology: the exact pattern is "
                 "step-sequence dependent (as with the RNG seed),\n"
                 "but the statistics (energy, domain scale, phases) "
                 "agree", fontsize=11, y=1.05)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    r = compare(dm, mesh, device=args.device)
    fig_dt_and_energy(r, "p2_adaptivity.png")
    fig_morph(r, "p2_morphology.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
