"""OrgElMorph course - Physics P3: figures + number macros, rendered
PURELY from a saved harness run directory (spec P3).

    PYTHONPATH=<repo>/src python gen_figures.py --run outputs/p3

Reads ``results.json`` (scalars) + ``history.npz`` (fields/trajectories)
from the run dir, writes ../../latex/figures/p3_*.png and
../../latex/numbers/p3.tex.  No physics is re-run here: the document's
figures and cited numbers ARE the harness output.
"""
import argparse
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p3.tex")

# figure order / labels for the 6 cases
CASE_ORDER = ["neutral", "attract", "repel", "opposing", "confined", "demix"]
CASE_LABEL = {
    "neutral": "neutral (no-flux)",
    "attract": r"attracting ($\phi^*{=}0.75$)",
    "repel": r"repelling ($\phi^*{=}0.25$)",
    "opposing": "opposing walls",
    "confined": "confined lateral",
    "demix": r"demixing+wetting ($\chi{=}2.7$)",
}


# --------------------------------------------------------------------------
# number macros
# --------------------------------------------------------------------------
def _sci(x):
    """\\ensuremath{m\\times10^{e}} for a positive magnitude x."""
    if x <= 0 or not np.isfinite(x):
        return r"\ensuremath{0}"
    m, e = f"{x:.1e}".split("e")
    return f"\\ensuremath{{{m}\\times10^{{{int(e)}}}}}"


def _drift(x):
    if x < 1e-13:
        return r"\ensuremath{<10^{-13}} (machine)"
    return _sci(x)


def write_numbers(res):
    cases = res["cases"]
    bd = res["bdlayer"]
    clip = res["clip"]

    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    def sub(k):
        return f"{cases[k]['substrate_phi']:.3f}"

    def enr(k):
        return f"{cases[k]['enrichment']:+.3f}"

    def num(x, fmt=".3f"):
        return f"\\ensuremath{{{format(x, fmt)}}}"

    lines = ["% AUTO-GENERATED by gen_figures.py from results.json - do not edit.",
             mac("PthreeChi", f"{res['chi']:g}"),
             mac("PthreeChiDemix", f"{res['chi_demix']:g}"),
             # per-case substrate composition + enrichment
             mac("PthreeNeutralSub", sub("neutral")),
             mac("PthreeNeutralEnr", enr("neutral")),
             mac("PthreeAttractSub", sub("attract")),
             mac("PthreeAttractEnr", enr("attract")),
             mac("PthreeRepelSub", sub("repel")),
             mac("PthreeRepelEnr", enr("repel")),
             mac("PthreeOpposingSub", sub("opposing")),
             mac("PthreeOpposingAir",
                 f"{cases['opposing']['air_phi']:.3f}"),
             mac("PthreeConfinedSub", sub("confined")),
             mac("PthreeConfinedEnr", enr("confined")),
             mac("PthreeDemixSub", sub("demix")),
             mac("PthreeDemixEnr", enr("demix")),
             # energy budget (attracting case)
             mac("PthreeFbulk", num(cases["attract"]["F_bulk"])),
             mac("PthreeFgrad", num(cases["attract"]["F_grad"], ".4f")),
             mac("PthreeFwall", num(cases["attract"]["F_wall"])),
             mac("PthreeFwallNeutral", num(cases["neutral"]["F_wall"])),
             mac("PthreeFwallDemix", num(cases["demix"]["F_wall"])),
             # conservation: quadrature-mass drift (max over all 6 cases);
             # projection stays inactive for the single-phase wells, and
             # fires only transiently in the demixing quench (reported
             # separately) with mass still conserved
             mac("PthreeMassdrift",
                 _drift(max(cases[k]["mass_drift"] for k in CASE_ORDER))),
             mac("PthreeMaxprojdof",
                 f"{max(cases[k]['projected_dofs'] for k in CASE_ORDER if k != 'demix')}"),
             mac("PthreeDemixProjdof", f"{cases['demix']['projected_dofs']}"),
             # boundary layer (from the clean stable-bulk kappa study)
             mac("PthreeBdKappaLo", f"{bd['kappa'][0]:g}"),
             mac("PthreeBdDeltaLo", num(bd["delta_1e"][0], ".3f")),
             mac("PthreeBdKappaHi", f"{bd['kappa'][-1]:g}"),
             mac("PthreeBdDeltaHi", num(bd["delta_1e"][-1], ".3f")),
             mac("PthreeDeltaSlope", num(bd["slope_1e"], ".2f")),
             mac("PthreeDeltaSlopeFit", num(bd["slope_fit"], ".2f")),
             # projection / clipping demonstration (violating IC)
             mac("PthreeClipAmp", f"{clip['clip_amp']:g}"),
             mac("PthreeClipProjdof", f"{clip['projected_dofs']}"),
             mac("PthreeClipMaxcorr", _sci(clip["max_correction"])),
             mac("PthreeClipDrift", _drift(clip["mass_drift"]))]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


# --------------------------------------------------------------------------
# figures
# --------------------------------------------------------------------------
def fig_fields(hist, fname):
    fig, axes = plt.subplots(2, 3, figsize=(11.4, 7.6), dpi=150)
    for ax, key in zip(axes.ravel(), CASE_ORDER):
        fld = hist[f"{key}_field"]          # grid[ix, iy], iy=0 = substrate
        im = ax.imshow(fld.T, origin="lower", cmap="viridis",
                       vmin=0.0, vmax=1.0, aspect="auto")
        ax.set_title(CASE_LABEL[key], fontsize=10)
        ax.set_xlabel("x"); ax.set_ylabel("y (height)")
        ax.set_xticks([]); ax.set_yticks([])
        ax.axhline(0.0, color="w", lw=3)     # substrate edge
    fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02, label=r"$\phi$")
    fig.suptitle("Substrate/air wall energy stratifies the morphology "
                 "(substrate = bottom white line)", fontsize=12, y=1.01)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_profiles(hist, fname):
    fig, ax = plt.subplots(figsize=(6.8, 4.4), dpi=150)
    styles = {"neutral": ("C7-", "neutral"),
              "attract": ("C3-", "attracting $g<0$"),
              "repel": ("C2-", "repelling"),
              "opposing": ("C0-", "opposing walls"),
              "confined": ("C4--", "confined lateral"),
              "demix": ("C1-", r"demixing ($\chi{=}2.7$)")}
    for key, (st, lab) in styles.items():
        prof = hist[f"{key}_profile"]
        ys = hist[f"{key}_ys"]
        y = (ys - ys.min()) / (ys.max() - ys.min())
        ax.plot(prof, y, st, lw=2, label=lab)
    ax.axhline(0.0, color="gray", ls=":", lw=1)
    ax.set_xlabel(r"lateral-mean $\phi(y)$")
    ax.set_ylabel("height $y$ (0 = substrate, 1 = air)")
    ax.set_title("Vertical enrichment profiles (6 boundary conditions)")
    ax.legend(fontsize=8, loc="center right"); ax.grid(alpha=0.3)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_energy(hist, res, fname):
    fig, axes = plt.subplots(1, 2, figsize=(11.2, 4.2), dpi=150)
    # (a) energy budget vs time for the attracting case
    ax = axes[0]
    t = hist["attract_t"]
    ax.plot(t, hist["attract_Ftot"], "k-", lw=2, label="total $F$")
    ax.plot(t, hist["attract_Fbulk"], "C0--", lw=1.5, label="bulk")
    ax.plot(t, hist["attract_Fgrad"], "C2-.", lw=1.5, label="gradient")
    ax.plot(t, hist["attract_Fwall"], "C3-", lw=1.5, label="wall")
    ax.set_xlabel("time $t$"); ax.set_ylabel("free energy")
    ax.set_title("Energy budget (attracting wall)")
    ax.legend(); ax.grid(alpha=0.3)
    # (b) F_wall decreasing as the wall enriches — across cases
    ax = axes[1]
    for key, c in (("neutral", "C7"), ("repel", "C2"), ("attract", "C3"),
                   ("demix", "C1")):
        ax.plot(hist[f"{key}_t"], hist[f"{key}_Fwall"], "-", color=c,
                lw=1.8, label=CASE_LABEL[key])
    ax.set_xlabel("time $t$"); ax.set_ylabel(r"wall energy $F_w$")
    ax.set_title(r"$F_w$ falls as the preferred component wets the wall")
    ax.legend(fontsize=8); ax.grid(alpha=0.3)
    fig.suptitle("Full free-energy budget $F=F_{bulk}+F_{grad}+F_{wall}$ "
                 "(all by quadrature)", fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_bdlayer(hist, res, fname):
    bd = res["bdlayer"]
    kappa = np.asarray(bd["kappa"])
    d1e = np.asarray(bd["delta_1e"])
    dfit = np.asarray(bd["delta_fit"])
    fig, axes = plt.subplots(1, 2, figsize=(11.2, 4.2), dpi=150)
    # (a) the near-wall excess profiles on the STABLE bulk (the clean
    #     boundary layer): thinnest (smallest kappa) vs thickest (largest)
    ax = axes[0]
    ys = hist["bd_excess_ys"]
    y = ys - ys.min()
    klo, khi = kappa[0], kappa[-1]
    ax.plot(hist["bd_excess_lo"], y, "C0-", lw=2,
            label=fr"$\kappa={klo:.0e}$ ($\delta={d1e[0]:.3f}$)")
    ax.plot(hist["bd_excess_hi"], y, "C3-", lw=2,
            label=fr"$\kappa={khi:.0e}$ ($\delta={d1e[-1]:.3f}$)")
    ax.set_xlabel(r"excess $\phi(y)-\phi_{\rm bulk}$")
    ax.set_ylabel("height $y$ (0 = substrate)")
    ax.set_ylim(0, 0.35)
    ax.set_title("Enrichment boundary layer (stable bulk)")
    ax.legend(fontsize=8); ax.grid(alpha=0.3)
    # (b) delta vs kappa — log-log with fitted slope
    ax = axes[1]
    ax.loglog(kappa, d1e, "C3o-", label=r"$\delta_{1/e}$")
    ax.loglog(kappa, dfit, "C0s--", label=r"$\delta_{\rm fit}$")
    guide = d1e[0] * np.sqrt(kappa / kappa[0])
    ax.loglog(kappa, guide, "k:", lw=1,
              label=r"$\propto\sqrt{\kappa}$ guide")
    ax.set_xlabel(r"$\kappa$"); ax.set_ylabel(r"boundary-layer $\delta$")
    ax.set_title(rf"$\delta\sim\kappa^{{{bd['slope_1e']:.2f}}}$ "
                 r"(expect $\kappa^{0.5}$)")
    ax.legend(fontsize=8); ax.grid(alpha=0.3, which="both")
    fig.suptitle("Boundary-layer thickness scales as "
                 r"$\delta\sim\sqrt{\kappa}$", fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default=os.path.join(os.path.dirname(__file__),
                                                  "outputs", "p3"),
                    help="harness run directory (results.json + history.npz)")
    args = ap.parse_args()
    with open(os.path.join(args.run, "results.json")) as fh:
        res = json.load(fh)
    hist = dict(np.load(os.path.join(args.run, "history.npz")))
    os.makedirs(FIGDIR, exist_ok=True)
    fig_fields(hist, "p3_fields.png")
    fig_profiles(hist, "p3_profiles.png")
    fig_energy(hist, res, "p3_energy.png")
    fig_bdlayer(hist, res, "p3_bdlayer.png")
    write_numbers(res)


if __name__ == "__main__":
    main()
