"""OrgElMorph course - Physics P3: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p3_*.png and ../../latex/numbers/p3.tex.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from substrate import build_mesh_dm, run

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p3.tex")

# quadratic wall well f_w = g*phi + h*phi^2 (preferred phi* = -g/2h)
CASES = [("neutral", 0.0, 0.0, "no-flux (neutral)"),
         ("attract", -1.5, 1.0, r"attracting ($\phi^*=0.75$)"),
         ("repel", -0.5, 1.0, r"repelling ($\phi^*=0.25$)")]


def write_numbers(res, chi):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    neu, att, rep = res["neutral"], res["attract"], res["repel"]
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PthreeChi", f"{chi:g}"),
             mac("PthreeNeutralSub", f"{neu['wall_phi'][-1]:.3f}"),
             mac("PthreeNeutralEnr",
                 f"{neu['wall_phi'][-1] - neu['bulk_phi'][-1]:+.3f}"),
             mac("PthreeAttractSub", f"{att['wall_phi'][-1]:.3f}"),
             mac("PthreeAttractEnr",
                 f"{att['wall_phi'][-1] - att['bulk_phi'][-1]:+.3f}"),
             mac("PthreeRepelSub", f"{rep['wall_phi'][-1]:.3f}"),
             mac("PthreeRepelEnr",
                 f"{rep['wall_phi'][-1] - rep['bulk_phi'][-1]:+.3f}"),
             mac("PthreeMassdrift",
                 f"{max(abs(r['mass_final'] - r['mass0']) for r in res.values()):.1e}"
                 .replace("e-0", r"\times10^{-").replace("e+0", r"\times10^{")
                 + "}")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def fig_fields(res, fname):
    fig, axes = plt.subplots(1, 3, figsize=(11.4, 4.0), dpi=150)
    for ax, (key, g, h, label) in zip(axes, CASES):
        fld = res[key]["snaps"][max(res[key]["snaps"])]
        im = ax.imshow(fld.T, origin="lower", cmap="viridis",
                       vmin=0.0, vmax=1.0)
        ax.set_title(label, fontsize=11)
        ax.set_xlabel("x"); ax.set_ylabel("y (height)")
        ax.set_xticks([]); ax.set_yticks([])
        ax.axhline(0.0, color="w", lw=3)      # substrate edge
    fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02, label=r"$\phi$")
    fig.suptitle("Substrate wall energy stratifies the morphology "
                 "(substrate = bottom white line)", fontsize=12, y=1.03)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_profiles(res, fname):
    fig, ax = plt.subplots(figsize=(6.6, 4.2), dpi=150)
    ny = len(res["neutral"]["yprofile"])
    y = np.linspace(0.0, 1.0, ny)
    styles = {"neutral": ("C0-", "no-flux (neutral)"),
              "attract": ("C3-", "attracting wall $g<0$"),
              "repel": ("C2-", "repelling wall $g>0$")}
    for key, (st, lab) in styles.items():
        ax.plot(res[key]["yprofile"], y, st, lw=2, label=lab)
    ax.axhline(0.0, color="gray", ls=":", lw=1)
    ax.set_xlabel(r"lateral-mean $\phi$")
    ax.set_ylabel("height $y$ (0 = substrate)")
    ax.set_title("Vertical enrichment profile")
    ax.legend(); ax.grid(alpha=0.3)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    ap.add_argument("--chi", type=float, default=2.2)
    ap.add_argument("--t_end", type=float, default=0.4)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    res = {}
    for key, g, h, _ in CASES:
        res[key] = run(dm, mesh, cons, wall_g=g, wall_h=h,
                       chi=args.chi, t_end=args.t_end, device=args.device)
    fig_fields(res, "p3_fields.png")
    fig_profiles(res, "p3_profiles.png")
    write_numbers(res, args.chi)


if __name__ == "__main__":
    main()
