"""OrgElMorph course - Differentiable D2: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and the cited numbers into
../../latex/numbers/d2.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from sensitivity import sensitivity, chi_sweep

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d2.tex")


def _sci(val, digits=3):
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    worst = max(r["rel_chi"], r["rel_kap"])
    lines = [
        "% AUTO-GENERATED by differentiable/02 gen_figures.py - do not edit.",
        mac("DtwoSteps", f"{r['n_steps']}"),
        mac("DtwoChi", f"{r['chi']:g}"),
        mac("DtwoKappa", f"{r['kappa']:g}"),
        mac("DtwoJ", _sci(r["J"])),
        mac("DtwoGradChi", _sci(r["dJdchi_adj"])),
        mac("DtwoGradKappa", _sci(r["dJdkap_adj"])),
        mac("DtwoRelFD", _sci(worst, 1)),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def morph_figure(r, fname):
    """The final morphology field whose scalar summary we differentiate."""
    fig, ax = plt.subplots(figsize=(4.6, 4.0), dpi=150)
    im = ax.imshow(r["morph"], origin="lower", cmap="viridis")
    ax.set_title(f"final morphology  ($\\chi={r['chi']:g}$, "
                 f"{r['n_steps']} steps)\n"
                 f"demixing amplitude $J={r['J']:.3g}$", fontsize=11)
    ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="$c$")
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def slope_figure(chis, J, slope, fname, dchi=0.12):
    """J(chi) sampled (dots) with the adjoint tangents (short segments of
    slope dJ/dchi) drawn at each point.  The tangents lie ALONG the curve
    - the gradient IS the local slope of the morphology response."""
    fig, ax = plt.subplots(figsize=(6.6, 4.4), dpi=150)
    ax.plot(chis, J, "o-", color="C0", lw=1.5,
            label=r"morphology $J(\chi)$")
    for i, x in enumerate(chis):
        xs = np.array([x - dchi, x + dchi])
        ys = J[i] + slope[i] * (xs - x)
        ax.plot(xs, ys, "-", color="C3", lw=2.2,
                label="adjoint tangent $dJ/d\\chi$" if i == 0 else None)
    ax.set_xlabel(r"Flory interaction $\chi$")
    ax.set_ylabel(r"demixing amplitude $J$")
    ax.set_title("The gradient is the slope of the morphology response")
    ax.legend()
    ax.grid(alpha=0.3)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    ap.add_argument("--steps", type=int, default=6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = sensitivity(level=args.level, n_steps=args.steps,
                    device=args.device)
    chis, J, slope = chi_sweep(level=args.level, n_steps=args.steps,
                               device=args.device)
    morph_figure(r, "d2_morphology.png")
    slope_figure(chis, J, slope, "d2_slope.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
