"""OrgElMorph course - Physics P5: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p5_*.png and ../../latex/numbers/p5.tex.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from evaporation import build_mesh_dm, run

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p5.tex")

RATES = [0.15, 0.3, 0.6]     # k_e (Biot number): slow -> fast drying
COLORS = ["C0", "C2", "C3"]


def fig_drying(res, fname):
    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(12.2, 4.2), dpi=150)
    for r, c in zip(res, COLORS):
        ax0.plot(r["t"], r["phis"], c, lw=2,
                 label=f"$k_e$ = {r['k_e']:g}")
        ax1.plot(r["t"], r["h"], c, lw=2, label=f"$k_e$ = {r['k_e']:g}")
    ax0.set_xlabel("time $t$"); ax0.set_ylabel(r"mean solvent $\phi_s$")
    ax0.set_title("Drying curves (faster $k_e$ dries sooner)")
    ax0.legend(); ax0.grid(alpha=0.3)
    ax1.set_xlabel("time $t$"); ax1.set_ylabel("film height $h(t)$")
    ax1.set_title("Film thins as solvent leaves")
    ax1.legend(); ax1.grid(alpha=0.3)
    fig.suptitle("Solvent evaporation sets the morphology clock",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_morph(res, fname):
    fig, axes = plt.subplots(1, len(res), figsize=(4.0 * len(res), 4.0),
                             dpi=150)
    for ax, r in zip(axes, res):
        gp, gf, h = r["snaps"]["final"]
        im = ax.imshow(gp.T, origin="lower", cmap="viridis",
                       vmin=0, vmax=max(0.5, gp.max()))
        ax.set_title(f"$k_e$ = {r['k_e']:g}\ndomain "
                     f"{r['domain_scale']:.1f}", fontsize=11)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02,
                 label=r"polymer $\phi_1$")
    fig.suptitle("Dried morphology vs evaporation rate: faster drying "
                 "freezes a finer pattern", fontsize=12, y=1.03)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(res):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    slow, mid, fast = res
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PfiveKeSlow", f"{slow['k_e']:g}"),
             mac("PfiveKeFast", f"{fast['k_e']:g}"),
             mac("PfiveTdrySlow", f"{slow['t_dry']:.2f}"),
             mac("PfiveTdryFast", f"{fast['t_dry']:.2f}"),
             mac("PfivePhisSlow", f"{slow['phis_final']:.3f}"),
             mac("PfivePhisFast", f"{fast['phis_final']:.3f}"),
             mac("PfiveDomSlow", f"{slow['domain_scale']:.2f}"),
             mac("PfiveDomFast", f"{fast['domain_scale']:.2f}"),
             mac("PfiveHslow", f"{slow['h_final']:.3f}"),
             mac("PfiveHfast", f"{fast['h_final']:.3f}")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    ap.add_argument("--t_end", type=float, default=6.0)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    res = [run(dm, mesh, cons, k_e=k, t_end=args.t_end,
               device=args.device) for k in RATES]
    fig_drying(res, "p5_drying.png")
    fig_morph(res, "p5_morphology.png")
    write_numbers(res)


if __name__ == "__main__":
    main()
