"""OrgElMorph course - Differentiable D1: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and the cited numbers into
../../latex/numbers/d1.tex (so the document's numbers ARE this run's
measured output - never hand-copied).  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from three_way import three_way, fd_stepsize_study

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d1.tex")

# Pretty math labels for the parameters (chi == the Flory B coefficient).
PRETTY = {"M": r"$M$", "kappa": r"$\kappa$", "B": r"$\chi$", "A": r"$A$"}


def _sci(val, digits=3):
    """A number as \\ensuremath{m\\times10^{e}} (mode-agnostic, so it works
    in text and math without nesting-$ errors - the P1 convention)."""
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r, eps, err):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    worst_tw = max(r["rel_tw"].values())
    worst_fd = max(r["rel_fd"].values())
    fd_floor = float(np.min(err))                # best |FD - adjoint|
    lines = [
        "% AUTO-GENERATED by differentiable/01 gen_figures.py - do not edit.",
        mac("DoneSteps", f"{r['n_steps']}"),
        mac("DoneSide", f"{r['side']}"),
        mac("DoneNn", f"{r['nn']}"),
        # the four adjoint gradients (with sign - direction of steepest J)
        mac("DoneGradM", _sci(r["grads"]["M"][0])),
        mac("DoneGradKappa", _sci(r["grads"]["kappa"][0])),
        mac("DoneGradChi", _sci(r["grads"]["B"][0])),
        mac("DoneGradA", _sci(r["grads"]["A"][0])),
        # the two agreement floors (the gate)
        mac("DoneAgreeTwin", _sci(worst_tw, 1)),
        mac("DoneAgreeFD", _sci(worst_fd, 1)),
        mac("DoneFDfloor", _sci(fd_floor, 1)),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def bars_agreement(r, fname):
    """Three bars per parameter - adjoint, twin, FD - visually coincident
    (that overlap IS the message: the three methods return one number)."""
    names = r["names"]
    x = np.arange(len(names))
    w = 0.26
    fig, ax = plt.subplots(figsize=(7.6, 4.4), dpi=150)
    adj = [r["grads"][p][0] for p in names]
    tw = [r["grads"][p][1] for p in names]
    fd = [r["grads"][p][2] for p in names]
    ax.bar(x - w, adj, w, label="adjoint", color="C0")
    ax.bar(x, tw, w, label="autograd twin", color="C2")
    ax.bar(x + w, fd, w, label="finite diff", color="C3")
    ax.axhline(0, color="k", lw=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels([PRETTY[p] for p in names], fontsize=13)
    ax.set_ylabel(r"$dJ/dp$")
    ax.set_title("Same gradient, three independent methods "
                 "(bars coincide)")
    ax.legend()
    ax.grid(axis="y", alpha=0.3)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fd_valley(eps, err, g_adj, fname):
    """The finite-difference step-size valley for dJ/dchi: |FD(e)-adjoint|
    vs e.  Large e -> truncation (falls); tiny e -> roundoff (rises).  The
    adjoint is exact (no step), so its error is the flat floor at the
    bottom - the pedagogical punchline."""
    fig, ax = plt.subplots(figsize=(6.6, 4.4), dpi=150)
    ax.loglog(eps, err, "o-", color="C3", label=r"$|\,$FD$(\epsilon)-$"
              r"adjoint$\,|$")
    ax.axhline(np.min(err), color="C0", ls="--",
               label="adjoint (exact, no step)")
    ax.set_xlabel(r"finite-difference step $\epsilon$")
    ax.set_ylabel(r"error in $dJ/d\chi$")
    ax.set_title("Finite differences must tune a step; the adjoint "
                 "need not")
    ax.legend()
    ax.grid(which="both", alpha=0.3)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    ap.add_argument("--steps", type=int, default=3)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = three_way(level=args.level, n_steps=args.steps, device=args.device)
    eps, err, g_adj = fd_stepsize_study(level=args.level,
                                        n_steps=args.steps, name="B",
                                        device=args.device)
    bars_agreement(r, "d1_agreement.png")
    fd_valley(eps, err, g_adj, "d1_fd_valley.png")
    write_numbers(r, eps, err)


if __name__ == "__main__":
    main()
