"""OrgElMorph course - Computational C4: figures + numbers.

Writes the live 2-D solver-crossover figure and a cited-3-D bar figure
into ../../latex/figures/, and the measured macros into
../../latex/numbers/c4.tex.  The 2-D numbers are live; the 3-D numbers
are cited from the dev notes (see solvers.CITED_3D).

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from solvers import benchmark_solvers_2d, CITED_3D, CITED_FACTS

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "c4.tex")


def crossover_figure(recs, fname):
    d = np.array([r["dofs"] for r in recs])
    s = np.array([r["splu_ms"] for r in recs])
    c = np.array([r["cudss_ms"] for r in recs])
    fig, ax = plt.subplots(figsize=(6.6, 4.6), dpi=150)
    ax.loglog(d, s, "o-", color="C0", lw=2, ms=8, label="splu (CPU direct)")
    ax.loglog(d, c, "s-", color="C3", lw=2, ms=8, label="cuDSS (GPU direct)")
    ax.set_xlabel("degrees of freedom (2-D)")
    ax.set_ylabel("linear solve: factorize + solve (ms)")
    ax.set_title("Direct-solver crossover in 2-D\n"
                 "(real Cahn--Hilliard Jacobian)")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def cited3d_figure(fname):
    """Bar chart of the cited 3-D per-solve cost: cuDSS vs blockch_dev,
    with the cuDSS ceiling marked."""
    cases = [c[0].split(" ")[0] for c in CITED_3D]
    cu = [c[2] for c in CITED_3D]
    bk = [c[3] for c in CITED_3D]
    x = np.arange(len(cases))
    fig, ax = plt.subplots(figsize=(6.8, 4.4), dpi=150)
    w = 0.38
    cu_plot = [v if v is not None else 0 for v in cu]
    ax.bar(x - w / 2, cu_plot, w, color="C3", label="cuDSS")
    ax.bar(x + w / 2, bk, w, color="C0", label="blockch\\_dev")
    for i, v in enumerate(cu):
        if v is None:
            ax.text(x[i] - w / 2, 1.0, "CEILING\n(48 GB)", ha="center",
                    va="bottom", fontsize=8, color="C3", rotation=0)
    ax.set_xticks(x); ax.set_xticklabels(cases, fontsize=9)
    ax.set_ylabel("per linear-solve (s/call)")
    ax.set_title("Cited 3-D scaling (dev notes): blockch wins where "
                 "cuDSS dies")
    ax.grid(True, axis="y", alpha=0.3)
    ax.legend()
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(recs):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    cross = next((r for r in recs if r["speedup"] > 1.0), recs[-1])
    big = recs[-1]
    lines = [
        "% AUTO-GENERATED by gen_figures.py - do not edit.",
        # live 2-D
        mac("CfourSmallDofs", f"{recs[0]['dofs']:,}".replace(",", r"{,}")),
        mac("CfourSmallSpeedup", f"{recs[0]['speedup']:.1f}"),
        mac("CfourBigDofs", f"{big['dofs']:,}".replace(",", r"{,}")),
        mac("CfourBigSpeedup", f"{big['speedup']:.1f}"),
        mac("CfourCrossDofs", f"{cross['dofs']:,}".replace(",", r"{,}")),
        # cited 3-D
        mac("CfourCudssCeiling",
            f"{CITED_FACTS['cudss_ceiling_dofs']:,}".replace(",", r"{,}")),
        mac("CfourBlockchSpeedup",
            f"{CITED_FACTS['blockch_slab64_speedup']:.1f}"),
        mac("CfourMaskedScall",
            f"{CITED_FACTS['masked_cudss_slab64_scall']:.2f}"),
        mac("CfourMatrixfreeDofs",
            f"{CITED_FACTS['matrixfree_dofs']:,}".replace(",", r"{,}")),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    recs = benchmark_solvers_2d(device=args.device)
    crossover_figure(recs, "c4_crossover.png")
    cited3d_figure("c4_cited3d.png")
    write_numbers(recs)


if __name__ == "__main__":
    main()
