"""OrgElMorph course - Physics P8: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p8_*.png and ../../latex/numbers/p8.tex.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from nucleation import build_mesh_dm, sweep

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p8.tex")


def fig_sweep(s, fname):
    runs = s["runs"]
    fig, axes = plt.subplots(1, 2, figsize=(12.0, 4.2), dpi=150)
    for r in runs:
        axes[0].plot(r["t"], r["X"], lw=2,
                     label=f"noise = {r['noise_psi']:g}")
    axes[0].set_xlabel("time $t$")
    axes[0].set_ylabel("crystalline fraction $X$")
    axes[0].set_title("Nucleation onset vs noise amplitude")
    axes[0].legend(); axes[0].grid(alpha=0.3)
    axes[1].plot(s["levels"], s["X_end"], "C3-o", ms=6)
    axes[1].set_xlabel("FDT noise amplitude (noise_psi)")
    axes[1].set_ylabel("final crystalline fraction $X$")
    axes[1].set_title("Threshold-like onset")
    axes[1].grid(alpha=0.3)
    fig.suptitle("Thermal noise is the physical seed of nucleation",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_fields(s, fname):
    runs = s["runs"]
    fig, axes = plt.subplots(1, len(runs), figsize=(3.4 * len(runs), 3.6),
                             dpi=150)
    for ax, r in zip(axes, runs):
        im = ax.imshow(r["psi"].T, origin="lower", cmap="magma",
                       vmin=0, vmax=1)
        ax.set_title(f"noise = {r['noise_psi']:g}\n$X$ = {r['X_end']:.3f}, "
                     f"{r['n_grains']} grains", fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02,
                 label=r"crystallinity $\psi$")
    fig.suptitle("More noise nucleates more grains (fixed undercooling, "
                 "same time)", fontsize=12, y=1.04)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(s):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    runs = s["runs"]
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PeightNlevels", f"{len(runs)}"),
             mac("PeightNoiseZero", f"{runs[0]['noise_psi']:g}"),
             mac("PeightXzero", f"{runs[0]['X_end']:.3f}"),
             mac("PeightNoiseHi", f"{runs[-1]['noise_psi']:g}"),
             mac("PeightXhi", f"{runs[-1]['X_end']:.3f}"),
             mac("PeightGrainsHi", f"{runs[-1]['n_grains']}")]
    # first noise level that nucleated (X_end > 0.02)
    onset = next((r["noise_psi"] for r in runs if r["X_end"] > 0.02),
                 None)
    lines.append(mac("PeightOnset",
                     "none" if onset is None else f"{onset:g}"))
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=5)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    s = sweep(dm, mesh, cons, device=args.device)
    fig_sweep(s, "p8_sweep.png")
    fig_fields(s, "p8_fields.png")
    write_numbers(s)


if __name__ == "__main__":
    main()
