"""OrgElMorph course - Differentiable D7 (capstone): inverse-design a process.

Importable core for the capstone.  Everything before this computed a
gradient or read one off; the capstone CLOSES THE LOOP: PDE-constrained
optimisation.  We DESIGN a temperature schedule T(t) that drives the
coupled Cahn-Hilliard x Allen-Cahn crystallisation to a TARGET crystalline
fraction, by minimising

    J(T) = 1/2 ( <psi_N>(T) - phi_target )^2

over the whole schedule, using the D4 time-series schedule gradient
dJ/dT_n and a bounded quasi-Newton optimiser (L-BFGS-B, T in [0.2, 2.0]).

The target is generated by a ground-truth cold ramp so it is reachable by
construction - which lets the tutorial CHECK that the designed process
actually hits it.  This is the same machinery a researcher would point at
a real specification ("give me 45% crystallinity with this domain size"):
the simulator, run backward, returns the recipe.
"""
import numpy as np
from scipy.optimize import minimize

from diffsim.octree.build import build_uniform
from diffsim.mesh.nodes import build_mesh
from diffsim.mesh.constraints import build_constraints
from diffsim.mesh.basis import basis_tables
from diffsim.assembly.operators import DeviceMesh
from diffsim.adjoint.phasefield import FHEnergy
from diffsim.adjoint.crystallization import CACHForward, CACHAdjoint

NF = 3

BASE = dict(M=1.0, kappa=0.02, eps2=0.02, L=1.0, dsig=1.0, dh=1.0, Tm=2.0,
            A=1.0, B=2.5)


def build_dm(level=3, device="cuda:0"):
    tree = build_uniform(level, dim=2)
    mesh = build_mesh(tree, p=1)
    cons = build_constraints(mesh)
    dm = DeviceMesh.from_mesh(mesh, cons, basis_tables(1, dim=2), device)
    return dm, mesh


def _ic(coords):
    cc = np.cos(np.pi * coords[:, 0]) * np.cos(np.pi * coords[:, 1])
    return 0.5 + 0.1 * cc, 0.2 + 0.05 * cc         # phi0, psi0


def march(dm, coords, Tsched, dt, order=2):
    phi0, psi0 = _ic(coords)
    f = CACHForward(dm, FHEnergy(BASE["A"], BASE["B"]), M=BASE["M"],
                    kappa=BASE["kappa"], eps2=BASE["eps2"], L=BASE["L"],
                    dsig=BASE["dsig"], dh=BASE["dh"], Tm=BASE["Tm"],
                    T=Tsched[0], dt=dt, order=order)
    f.set_initial(phi0, psi0)
    f.set_schedule(list(Tsched), bT=0.0)           # T -> crystallisation only
    f.run(len(Tsched))
    return f


def crystalline_fraction(f):
    return float(np.mean(f.steps[-1]["x"][2::NF]))


def obj_and_grad(dm, coords, Tsched, target, dt, order, nn):
    """J = 1/2 (<psi_N> - target)^2 and its schedule gradient dJ/dT_n
    (D4 machinery: one reverse sweep)."""
    f = march(dm, coords, Tsched, dt, order)
    m = crystalline_fraction(f)
    J = 0.5 * (m - target) ** 2
    dJ = [np.zeros(NF * nn) for _ in range(len(Tsched))]
    dJ[-1][2::NF] = (m - target) / nn              # d<psi_N>/dpsi_i = 1/nn
    gT = CACHAdjoint(f).temperature_gradient(dJ)
    return J, gT, m


def design(level=3, NS=6, dt=0.02, order=2, device="cuda:0",
           T_gt_lo=0.5, T_gt_hi=0.3, T0_val=1.0, bounds=(0.2, 2.0)):
    """Generate a reachable target from a ground-truth cold ramp, then
    design a schedule from a flat initial guess to hit it.  Returns the
    objective/achieved trajectories and the optimised schedule."""
    dm, mesh = build_dm(level, device)
    coords = mesh.node_coords
    nn = dm.n_nodes

    T_gt = np.linspace(T_gt_lo, T_gt_hi, NS)       # ground-truth cold ramp
    target = crystalline_fraction(march(dm, coords, T_gt, dt, order))

    hist = dict(J=[], achieved=[])

    def fg(T):
        J, gT, m = obj_and_grad(dm, coords, T, target, dt, order, nn)
        return J, gT

    def cb(T):
        J, _, m = obj_and_grad(dm, coords, T, target, dt, order, nn)
        hist["J"].append(J)
        hist["achieved"].append(m)

    T0 = np.full(NS, T0_val)
    J0, _, m0 = obj_and_grad(dm, coords, T0, target, dt, order, nn)
    hist["J"].append(J0)
    hist["achieved"].append(m0)
    res = minimize(fg, T0, jac=True, method="L-BFGS-B",
                   bounds=[bounds] * NS, callback=cb,
                   options=dict(maxiter=200, ftol=1e-20, gtol=1e-15))
    T_opt = res.x
    achieved = crystalline_fraction(march(dm, coords, T_opt, dt, order))
    return dict(target=target, achieved=achieved,
                diff=abs(achieved - target), J0=float(J0),
                Jend=float(res.fun), T_gt=T_gt, T0=T0, T_opt=T_opt,
                J_hist=np.asarray(hist["J"]),
                achieved_hist=np.asarray(hist["achieved"]),
                NS=NS, n_iter=len(hist["J"]), m0=float(m0),
                side=int(round(np.sqrt(nn))))


def fd_check(level=3, NS=6, dt=0.02, order=2, device="cuda:0"):
    """FD-verify the design objective's schedule gradient at the flat
    initial guess (the self-check the optimiser relies on)."""
    dm, mesh = build_dm(level, device)
    coords = mesh.node_coords
    nn = dm.n_nodes
    T_gt = np.linspace(0.5, 0.3, NS)
    target = crystalline_fraction(march(dm, coords, T_gt, dt, order))
    T0 = np.full(NS, 1.0)
    _, gT_adj, _ = obj_and_grad(dm, coords, T0, target, dt, order, nn)
    gT_fd = np.zeros(NS)
    for i in range(NS):
        e = 1e-6
        hi = T0.copy(); hi[i] += e
        lo = T0.copy(); lo[i] -= e
        Jh, _, _ = obj_and_grad(dm, coords, hi, target, dt, order, nn)
        Jl, _, _ = obj_and_grad(dm, coords, lo, target, dt, order, nn)
        gT_fd[i] = (Jh - Jl) / (2 * e)
    rel = np.abs(gT_adj - gT_fd) / np.maximum(np.abs(gT_fd), 1e-14)
    return gT_adj, gT_fd, rel
