"""OrgElMorph course - Differentiable D7: render the figures + numbers.

Writes PNGs into ../../latex/figures/ and numbers into
../../latex/numbers/d7.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from design import design

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "d7.tex")


def _sci(val, digits=2):
    if val == 0.0:
        return r"\ensuremath{0}"
    m, e = f"{val:.{digits}e}".split("e")
    return rf"\ensuremath{{{m}\times10^{{{int(e)}}}}}"


def write_numbers(r):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    lines = [
        "% AUTO-GENERATED by differentiable/07 gen_figures.py - do not edit.",
        mac("DsevenSteps", f"{r['NS']}"),
        mac("DsevenIter", f"{r['n_iter']}"),
        mac("DsevenTarget", f"{r['target']:.5f}"),
        mac("DsevenAchieved", f"{r['achieved']:.5f}"),
        mac("DsevenMzero", f"{r['m0']:.5f}"),
        mac("DsevenDiff", _sci(r["diff"], 1)),
        mac("DsevenJstart", _sci(r["J0"], 2)),
        mac("DsevenJend", _sci(r["Jend"], 1)),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def design_figure(r, fname):
    """Left: the schedules - flat initial guess, the designed T(t), and the
    ground-truth ramp that set the target. Right: the design objective
    collapsing as the achieved crystalline fraction reaches the target."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.0, 4.2), dpi=150)
    steps = np.arange(r["NS"])

    ax1.plot(steps, r["T0"], "s--", color="C0", lw=1.6,
             label="initial guess (flat)")
    ax1.plot(steps, r["T_opt"], "o-", color="C3", lw=2.0,
             label="designed $T(t)$")
    ax1.plot(steps, r["T_gt"], "^:", color="C7", lw=1.6,
             label="ground-truth ramp")
    ax1.set_xlabel("process step $n$")
    ax1.set_ylabel("temperature $T_n$")
    ax1.set_title("The designed quench schedule")
    ax1.set_xticks(steps)
    ax1.legend()
    ax1.grid(alpha=0.3)

    it = np.arange(r["J_hist"].size)
    ax2.semilogy(it, r["J_hist"], "o-", color="C0", lw=1.6)
    ax2.set_xlabel("optimiser evaluation")
    ax2.set_ylabel(r"design objective $J=\frac{1}{2}(\langle\psi\rangle"
                   r"-\phi^\star)^2$")
    ax2.set_title(f"Objective collapses "
                  f"(achieved $\\to$ target ${r['target']:.4f}$)")
    ax2.grid(which="both", alpha=0.3)
    axb = ax2.twinx()
    axb.plot(it, r["achieved_hist"], "D-", color="C2", lw=1.4, ms=5,
             label="achieved fraction")
    axb.axhline(r["target"], color="k", ls=":", lw=1.2, label="target")
    axb.set_ylabel(r"crystalline fraction $\langle\psi\rangle$",
                   color="C2")
    axb.tick_params(axis="y", labelcolor="C2")
    axb.legend(loc="center right", fontsize=9)

    fig.suptitle("Capstone: inverse-designing a process route to a target "
                 "crystallinity", fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=3)
    ap.add_argument("--steps", type=int, default=6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    r = design(level=args.level, NS=args.steps, device=args.device)
    design_figure(r, "d7_design.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
