"""Chapter 02 — centerline figure + numbers/c2.tex from a saved harness run.

    python run.py --config configs/ldc.yaml --mode reference --output outputs/ldc --overwrite
    python gen_figures.py --run-dir outputs/ldc

Writes latex/figures/c2_centerline.png and latex/numbers/c2.tex (the macros
the course document cites for Chapter 2).
"""
from __future__ import annotations

import argparse
import json
import os

import numpy as np

HERE = os.path.dirname(__file__)
FIGDIR = os.path.join(HERE, "..", "latex", "figures")
NUMTEX = os.path.join(HERE, "..", "latex", "numbers", "c2.tex")


def load(run_dir):
    with open(os.path.join(run_dir, "results.json")) as fh:
        results = json.load(fh)
    hist = {}
    hpath = os.path.join(run_dir, "history.npz")
    if os.path.exists(hpath):
        hist = dict(np.load(hpath))
    return results, hist


def centerline_fig(results, fname):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    y = np.asarray(results["ghia_y"])
    fig, ax = plt.subplots(figsize=(4.2, 4.2))
    ax.plot(results["u_proj"], y, "-o", ms=3, label="projection", color="#0a5aa0")
    ax.plot(results["u_mono"], y, "-s", ms=3, label="monolithic (oracle)",
            color="#a83232")
    ax.plot(results["ghia"], y, "k^", ms=4, label="Ghia (1982)")
    ax.set_xlabel(r"$u_x$ at $x=0.5$")
    ax.set_ylabel(r"$y$")
    ax.set_title(f"Lid-driven cavity, Re={results['Re']}, "
                 f"{results['side']}$\\times${results['side']}")
    ax.legend(fontsize=8, loc="upper left")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    os.makedirs(os.path.dirname(fname), exist_ok=True)
    fig.savefig(fname, dpi=150)
    print(f"wrote {fname}")


def write_numbers(results):
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    lid = results.get("u_proj_lid", results["u_proj"][1])
    with open(NUMTEX, "w") as fh:
        fh.write("% Chapter 2 measured numbers (generated by "
                 "02_pressure_projection/gen_figures.py)\n")
        fh.write(f"\\providecommand{{\\LdcProjMono}}{{{results['d_proj_mono']:.4f}}}\n")
        fh.write(f"\\providecommand{{\\LdcProjGhia}}{{{results['d_proj_ghia']:.4f}}}\n")
        fh.write(f"\\providecommand{{\\LdcMonoGhia}}{{{results['d_mono_ghia']:.4f}}}\n")
        fh.write(f"\\providecommand{{\\LdcProjLid}}{{{results['u_proj'][1]:.4f}}}\n")
        fh.write(f"\\providecommand{{\\LdcMonoLid}}{{{results['u_mono'][1]:.4f}}}\n")
        fh.write(f"\\providecommand{{\\LdcGhiaLid}}{{{results['ghia'][1]:.4f}}}\n")
        fh.write(f"\\providecommand{{\\LdcDivProj}}{{{results['div_proj']:.3f}}}\n")
        fh.write(f"\\providecommand{{\\LdcDivMono}}{{{results['div_mono']:.3f}}}\n")
    print(f"wrote {NUMTEX}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", default=os.path.join(HERE, "outputs", "ldc"))
    args = ap.parse_args()
    results, _hist = load(args.run_dir)
    centerline_fig(results, os.path.join(FIGDIR, "c2_centerline.png"))
    write_numbers(results)


if __name__ == "__main__":
    main()
