"""OrgElMorph course - Physics P9: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p9_*.png and ../../latex/numbers/p9.tex.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from arc import build_mesh_dm, run_arc

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p9.tex")


def fig_arc(dry, fname):
    """The stage strip (wet -> implant -> final) plus the drying/area
    histories, for the growing (dry-implant) run."""
    stages = [("wet film", dry["snaps"]["wet"]),
              ("seed implant", dry["snaps"]["implant"]),
              ("crystalline film", dry["snaps"]["final"])]
    fig, axes = plt.subplots(2, 3, figsize=(12.0, 7.4), dpi=150)
    for ax, (title, (gf, gpsi, h)) in zip(axes[0], stages):
        im = ax.imshow(gf.T, origin="lower", cmap="viridis",
                       vmin=0, vmax=max(0.6, gf.max()))
        ax.contour(gpsi.T, levels=[0.5], colors="r", linewidths=1.0)
        ax.set_title(title, fontsize=11); ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=list(axes[0]), fraction=0.02, pad=0.02,
                 label=r"small-molecule $\phi_0$ (crystal outline red)")
    ax = axes[1, 0]
    ax.plot(dry["t"], dry["phis"], "C0-", lw=2)
    ax.set_xlabel("time $t$"); ax.set_ylabel(r"mean solvent $\phi_s$")
    ax.set_title("drying"); ax.grid(alpha=0.3)
    ax = axes[1, 1]
    ax.plot(dry["t"], dry["area"], "C3-", lw=2)
    ax.set_xlabel("time $t$"); ax.set_ylabel("crystalline area")
    ax.set_title("crystallization"); ax.grid(alpha=0.3)
    ax = axes[1, 2]
    gf, gpsi, h = dry["snaps"]["final"]
    im2 = ax.imshow(gpsi.T, origin="lower", cmap="magma", vmin=0, vmax=1)
    ax.set_title("final crystallinity $\\psi$", fontsize=11)
    ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im2, ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle("The evaporation-induced crystallization arc: wet film "
                 "-> phase separation -> nucleation -> crystalline film",
                 fontsize=12, y=1.0)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_wet_vs_dry(wet, dry, fname):
    fig, axes = plt.subplots(1, 2, figsize=(8.4, 4.1), dpi=150)
    for ax, (r, lab) in zip(axes, [(wet, "WET implant"),
                                   (dry, "DRY implant")]):
        gf, gpsi, h = r["snaps"]["final"]
        ax.imshow(gf.T, origin="lower", cmap="viridis", vmin=0,
                  vmax=max(0.6, gf.max()))
        ax.contour(gpsi.T, levels=[0.5], colors="r", linewidths=1.2)
        ax.set_title(f"{lab}\n$\\phi_s$={r['phis_implant']:.2f} at implant, "
                     f"area {r['area_final']:.3f}", fontsize=10)
        ax.set_xticks([]); ax.set_yticks([])
    fig.suptitle("Same seeds: dissolve when wet, grow when dry "
                 "(evaporation-induced)", fontsize=12, y=1.03)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(wet, dry):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PnineWetPhis", f"{wet['phis_implant']:.3f}"),
             mac("PnineWetStart", f"{wet['area_implant']:.4f}"),
             mac("PnineWetEnd", f"{wet['area_final']:.4f}"),
             mac("PnineWetPsimax", f"{wet['psi_max']:.2f}"),
             mac("PnineDryPhis", f"{dry['phis_implant']:.3f}"),
             mac("PnineDryStart", f"{dry['area_implant']:.4f}"),
             mac("PnineDryEnd", f"{dry['area_final']:.4f}"),
             mac("PnineDryPsimax", f"{dry['psi_max']:.2f}"),
             mac("PnineKe", f"{dry['k_e']:g}")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=5)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    wet = run_arc(dm, mesh, cons, wet=True, device=args.device)
    dry = run_arc(dm, mesh, cons, wet=False, device=args.device)
    fig_arc(dry, "p9_arc.png")
    fig_wet_vs_dry(wet, dry, "p9_wet_vs_dry.png")
    write_numbers(wet, dry)


if __name__ == "__main__":
    main()
