"""OrgElMorph course - Physics P6: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p6_*.png and ../../latex/numbers/p6.tex.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from crystallization import (build_mesh_dm, run_grow_melt, run_avrami, TM)

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p6.tex")


def fig_grow_melt(grow, melt, fname):
    fig, axes = plt.subplots(1, 3, figsize=(12.6, 4.0), dpi=150)
    axes[0].plot(grow["t"], grow["area"], "C3-o", ms=3,
                 label="T = 333 K (< Tm): grows")
    axes[0].plot(melt["t"], melt["area"], "C0-s", ms=3,
                 label="T = 700 K (> Tm): melts")
    axes[0].set_xlabel("time $t$")
    axes[0].set_ylabel("crystalline area fraction")
    axes[0].set_title("Growth below Tm, melting above")
    axes[0].legend(); axes[0].grid(alpha=0.3)
    for ax, r, lab in ((axes[1], grow, "grown (T < Tm)"),
                       (axes[2], melt, "melted (T > Tm)")):
        im = ax.imshow(r["psi"].T, origin="lower", cmap="magma",
                       vmin=0, vmax=1)
        ax.set_title(lab, fontsize=11); ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=[axes[1], axes[2]], fraction=0.02, pad=0.02,
                 label=r"crystallinity $\psi$")
    fig.suptitle("Seeded crystal: the driving force changes sign at Tm",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_avrami(av, fname):
    fig, axes = plt.subplots(1, 3, figsize=(13.0, 4.0), dpi=150)
    t, X = av["t"], av["X"]
    axes[0].plot(t, X, "C2-o", ms=3)
    axes[0].set_xlabel("time $t$"); axes[0].set_ylabel("crystalline fraction $X$")
    axes[0].set_title("JMAK sigmoid"); axes[0].grid(alpha=0.3)
    # Avrami linearization
    m = (X > 0.05) & (X < 0.9) & (t > 1e-6)
    if m.sum() >= 2:
        axes[1].plot(np.log(t[m]), np.log(-np.log(1 - X[m])), "C2o", ms=4)
        xx = np.log(t[m])
        axes[1].plot(xx, av["n_avrami"] * xx
                     + (np.log(-np.log(1 - X[m])) - av["n_avrami"] * xx).mean(),
                     "k--", lw=1.2, label=f"slope n = {av['n_avrami']:.2f}")
        axes[1].legend()
    axes[1].set_xlabel(r"$\ln t$")
    axes[1].set_ylabel(r"$\ln(-\ln(1-X))$")
    axes[1].set_title("Avrami exponent (slope)"); axes[1].grid(alpha=0.3)
    im = axes[2].imshow(av["theta"].T, origin="lower", cmap="hsv",
                        vmin=0, vmax=1)
    axes[2].contour(av["psi"].T, levels=[0.5], colors="k", linewidths=0.8)
    axes[2].set_title("grains (orientation $\\theta$)", fontsize=11)
    axes[2].set_xticks([]); axes[2].set_yticks([])
    fig.colorbar(im, ax=axes[2], fraction=0.046, pad=0.04, label=r"$\theta$")
    fig.suptitle("Avrami / JMAK crystallization kinetics and grains",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(grow, melt, av):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PsixTm", f"{TM:g}"),
             mac("PsixGrowStart", f"{grow['a0']:.4f}"),
             mac("PsixGrowEnd", f"{grow['a1']:.4f}"),
             mac("PsixGrowRatio", f"{grow['a1'] / max(grow['a0'], 1e-9):.2f}"),
             mac("PsixMeltStart", f"{melt['a0']:.4f}"),
             mac("PsixMeltEnd", f"{melt['a1']:.4f}"),
             mac("PsixAvramiN", f"{av['n_avrami']:.2f}"),
             mac("PsixAvramiXend", f"{av['X_end']:.3f}"),
             mac("PsixSeeds", f"{av['n_seeds']}"),
             mac("PsixGrains", f"{av['n_grains']}")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    grow = run_grow_melt(dm, mesh, cons, 333.0, device=args.device)
    melt = run_grow_melt(dm, mesh, cons, 700.0, device=args.device)
    av = run_avrami(dm, mesh, cons, device=args.device)
    fig_grow_melt(grow, melt, "p6_grow_melt.png")
    fig_avrami(av, "p6_avrami.png")
    write_numbers(grow, melt, av)


if __name__ == "__main__":
    main()
