"""OrgElMorph course - C7: figures + numbers from the saved harness run.

    python run.py --config configs/c7.yaml --device cuda:0 --solver splu \\
        --output outputs/c7 --overwrite --mode reference
    python gen_figures.py --run-dir outputs/c7
"""
import argparse
import json
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = os.path.dirname(__file__)
FIGDIR = os.path.join(HERE, "..", "..", "latex", "figures")
NUMTEX = os.path.join(HERE, "..", "..", "latex", "numbers", "c7.tex")


def load(run_dir):
    with open(os.path.join(run_dir, "results.json")) as fh:
        results = json.load(fh)
    hist = dict(np.load(os.path.join(run_dir, "history.npz"), allow_pickle=True))
    return results, hist


def breakdown_fig(results, hist, fname):
    """Where a step's time goes (factor-dominated) + device-memory accounting."""
    fig, ax = plt.subplots(1, 2, figsize=(11.5, 4.4), dpi=140)
    labels = [str(s) for s in hist["break_labels"]]
    vals = np.asarray(hist["break_ms"], dtype=float)
    colors = ["#c0392b", "#e67e22", "#2980b9"]
    ax[0].barh(range(len(vals)), vals, color=colors)
    ax[0].set_yticks(range(len(vals))); ax[0].set_yticklabels(labels)
    ax[0].invert_yaxis()
    ax[0].set_xlabel("time per step (ms)")
    ax[0].set_title(f"One CH step = {results['step_ms']:.0f} ms: "
                    f"host LU factorisation dominates")
    for i, v in enumerate(vals):
        ax[0].text(v, i, f" {v:.0f} ms", va="center", fontsize=9)
    # right: device-memory accounting
    mlabels = [str(s) for s in hist["mem_labels"]]
    mvals = np.asarray(hist["mem_mb"], dtype=float)
    order = np.argsort(mvals)[::-1]
    ax[1].bar(range(len(mvals)), mvals[order], color="#16a085")
    ax[1].set_xticks(range(len(mvals)))
    ax[1].set_xticklabels([mlabels[i] for i in order], rotation=30, ha="right",
                          fontsize=8)
    ax[1].set_ylabel("device memory (MB)")
    ax[1].set_title(f"Device-memory accounting: Ae buffer dominates "
                    f"({results['analytical_mb']:.1f} MB total)")
    for i, v in enumerate(mvals[order]):
        ax[1].text(i, v, f"{v:.2f}", ha="center", va="bottom", fontsize=8)
    fig.suptitle("C7: profiling one Cahn-Hilliard step -- time and memory",
                 fontsize=12, y=1.02)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def bandwidth_fig(results, hist, fname):
    """Device memory bandwidth vs host<->device PCIe copy bandwidth."""
    fig, ax = plt.subplots(figsize=(6.8, 4.6), dpi=140)
    mb = np.asarray(hist["bw_copy_mb"], dtype=float)
    h2d = np.asarray(hist["bw_h2d"], dtype=float)
    d2h = np.asarray(hist["bw_d2h"], dtype=float)
    dev = float(hist["bw_device_gbs"][0])
    ax.axhline(dev, color="#c0392b", ls="-", lw=2.2,
               label=f"device memory triad ({dev:.0f} GB/s)")
    ax.plot(mb, h2d, "C0o-", lw=1.8, ms=6, label="PCIe H2D copy")
    ax.plot(mb, d2h, "C1s-", lw=1.8, ms=6, label="PCIe D2H copy")
    ax.set_xscale("log")
    ax.set_xlabel("copy size (MB)")
    ax.set_ylabel("achieved bandwidth (GB/s)")
    ax.set_title(f"Data movement rules: device BW is {results['bw_ratio']:.0f}x "
                 f"the PCIe link\n(triad AI {results['device_ai']:.3f} "
                 f"flop/byte -- memory-bound)")
    ax.legend(); ax.grid(alpha=0.3, which="both")
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(results):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    def sci(x, sig=2):
        mant, exp = f"{float(x):.{sig-1}e}".split("e")
        return f"\\ensuremath{{{mant}\\times10^{{{int(exp)}}}}}"

    nv_w = results.get("nvtx_warmup_ms") or 0.0
    nv_s = results.get("nvtx_step_ms") or 0.0
    lines = [
        "% AUTO-GENERATED by gen_figures.py from results.json - do not edit.",
        mac("CsevenStepMs", f"{results['step_ms']:.0f}"),
        mac("CsevenNewtonIters", f"{results['newton_iters']}"),
        mac("CsevenDofs", f"{results['dofs']}"),
        mac("CsevenNnz", f"{results['nnz']}"),
        mac("CsevenLaunchUs", f"{results['launch_us']:.0f}"),
        mac("CsevenDeviceGbs", f"{results['device_gbs']:.0f}"),
        mac("CsevenDeviceAI", f"{results['device_ai']:.3f}"),
        mac("CsevenPcieGbs", f"{results['pcie_gbs']:.0f}"),
        mac("CsevenBwRatio", f"{results['bw_ratio']:.0f}"),
        mac("CsevenFactorMs", f"{results['factor_ms']:.0f}"),
        mac("CsevenSolveMs", f"{results['solve_ms']:.1f}"),
        mac("CsevenFactorRatio", f"{results['factor_over_solve']:.0f}"),
        mac("CsevenDtwohPerStep", f"{results['d2h_per_step_mb']:.0f}"),
        mac("CsevenDriverMb", f"{(results['driver_mb'] or 0.0):.1f}"),
        mac("CsevenAnalyticalMb", f"{results['analytical_mb']:.2f}"),
        mac("CsevenAeMb", f"{results['ae_buffer_mb']:.2f}"),
        mac("CsevenNvtxWarmup", f"{nv_w:.0f}"),
        mac("CsevenNvtxStep", f"{nv_s:.0f}"),
        mac("CsevenNsysCaptured",
            "yes" if results.get("nsys_captured") else "no"),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", default=os.path.join(HERE, "outputs", "c7"))
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    results, hist = load(args.run_dir)
    breakdown_fig(results, hist, "c7_breakdown.png")
    bandwidth_fig(results, hist, "c7_bandwidth.png")
    write_numbers(results)


if __name__ == "__main__":
    main()
