"""OrgElMorph course - Computational C1: figures + numbers.

Writes two log-log convergence plots into ../../latex/figures/ and the
measured macros into ../../latex/numbers/c1.tex.  Same core as run.py, so
the document's numbers ARE the measured output of this run.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from convergence import spatial_mms, temporal_convergence

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "c1.tex")


def spatial_figure(recs, fname):
    fig, ax = plt.subplots(figsize=(6.4, 4.6), dpi=150)
    for r, mk, col in zip(recs, ("o", "s"), ("C0", "C3")):
        h, e = np.array(r["h"]), np.array(r["errs"])
        ax.loglog(h, e, mk + "-", color=col, lw=2, ms=8,
                  label=f"$p={r['p']}$ (order {r['order']:.2f})")
        # reference triangle at the ideal slope p+1
        ref = e[0] * (h / h[0]) ** (r["p"] + 1)
        ax.loglog(h, ref, "--", color=col, alpha=0.5,
                  label=f"slope ${r['p'] + 1}$ (ideal)")
    ax.set_xlabel("mesh size $h$")
    ax.set_ylabel(r"$L^2$ error $\|c_h - c^\ast\|$")
    ax.set_title("Spatial convergence (manufactured solution)")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def temporal_figure(recs, fname):
    fig, ax = plt.subplots(figsize=(6.4, 4.6), dpi=150)
    for r, mk, col in zip(recs, ("o", "s"), ("C0", "C3")):
        d, e = np.array(r["dts"]), np.array(r["errs"])
        name = "BDF1" if r["order"] == 1 else "BDF2"
        ax.loglog(d, e, mk + "-", color=col, lw=2, ms=8,
                  label=f"{name} (order {r['order_est']:.2f})")
        ref = e[0] * (d / d[0]) ** r["order"]
        ax.loglog(d, ref, "--", color=col, alpha=0.5,
                  label=f"slope ${r['order']}$ (ideal)")
    ax.set_xlabel(r"time step $\Delta t$")
    ax.set_ylabel(r"error vs.\ fine reference $\|c-c_{\mathrm{ref}}\|_\infty$")
    ax.set_title("Temporal convergence (fixed mesh)")
    ax.grid(True, which="both", alpha=0.3)
    ax.legend()
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def sci(val):
    """Format a small number as LaTeX $m\\times10^{e}$."""
    m, e = f"{val:.1e}".split("e")
    return rf"${m}\times10^{{{int(e)}}}$"


def write_numbers(sp, tp):
    """Emit numbers/c1.tex so the document's cited orders ARE this run's
    measured output.  LaTeX macro names must be letters only."""
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    lines = [
        "% AUTO-GENERATED by gen_figures.py - do not edit.",
        # spatial mean orders (should be ~ p+1)
        mac("ConeSpaPoneOrder", f"{sp[1]['order']:.2f}"),
        mac("ConeSpaPtwoOrder", f"{sp[2]['order']:.2f}"),
        mac("ConeSpaPoneOrderLo", f"{min(sp[1]['orders']):.2f}"),
        mac("ConeSpaPoneOrderHi", f"{max(sp[1]['orders']):.2f}"),
        # spatial errors (coarsest -> finest, per degree)
        mac("ConeSpaPoneErrCoarse", sci(sp[1]["errs"][0])),
        mac("ConeSpaPoneErrFine", sci(sp[1]["errs"][-1])),
        mac("ConeSpaPtwoErrCoarse", sci(sp[2]["errs"][0])),
        mac("ConeSpaPtwoErrFine", sci(sp[2]["errs"][-1])),
        # temporal mean orders (BDF1 ~1, BDF2 ~2)
        mac("ConeBdfoneOrder", f"{tp[1]['order_est']:.2f}"),
        mac("ConeBdftwoOrder", f"{tp[2]['order_est']:.2f}"),
        mac("ConeBdfoneErrCoarse", sci(tp[1]["errs"][0])),
        mac("ConeBdfoneErrFine", sci(tp[1]["errs"][-1])),
        mac("ConeBdftwoErrCoarse", sci(tp[2]["errs"][0])),
        mac("ConeBdftwoErrFine", sci(tp[2]["errs"][-1])),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)

    sp = {p: spatial_mms(p, levels, device=args.device)
          for p, levels in ((1, (4, 5, 6)), (2, (3, 4)))}
    spatial_figure([sp[1], sp[2]], "c1_spatial.png")

    dts = (8e-3, 4e-3, 2e-3)
    tp = {o: temporal_convergence(o, dts, device=args.device)
          for o in (1, 2)}
    temporal_figure([tp[1], tp[2]], "c1_temporal.png")

    write_numbers(sp, tp)


if __name__ == "__main__":
    main()
