"""OrgElMorph course - Physics P7: figures + numbers macros.

    python gen_figures.py --device cuda:0

Writes ../../latex/figures/p7_*.png and ../../latex/numbers/p7.tex.
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from coupled import build_mesh_dm, run

FIGDIR = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "figures")
NUMTEX = os.path.join(os.path.dirname(__file__), "..", "..", "latex",
                      "numbers", "p7.tex")


def fig_demix(on, off, fname):
    fig, axes = plt.subplots(1, 3, figsize=(12.6, 4.0), dpi=150)
    im0 = axes[0].imshow(off["phi0"].T, origin="lower", cmap="viridis",
                         vmin=0, vmax=1)
    axes[0].set_title("crystallization OFF\n($\\phi_0$, pure-CH)",
                      fontsize=11)
    im1 = axes[1].imshow(on["phi0"].T, origin="lower", cmap="viridis",
                         vmin=0, vmax=1)
    axes[1].set_title("crystallization ON\n($\\phi_0$)", fontsize=11)
    axes[2].imshow(on["phi0"].T, origin="lower", cmap="viridis",
                   vmin=0, vmax=1)
    axes[2].contour(on["psi"].T, levels=[0.5], colors="r", linewidths=1.2)
    axes[2].set_title("ON: crystal outline (red)\non $\\phi_0$",
                      fontsize=11)
    for ax in axes:
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im1, ax=axes, fraction=0.02, pad=0.02,
                 label=r"$\phi_0$ (crystallizer)")
    fig.suptitle("Crystallization-driven demixing: the crystal purifies "
                 "its species (sharper $\\phi_0$ than pure CH)",
                 fontsize=12, y=1.03)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def fig_ladder(res, fname):
    fig, axes = plt.subplots(1, len(res), figsize=(4.0 * len(res), 4.0),
                             dpi=150)
    for ax, (label, r) in zip(axes, res):
        ax.imshow(r["phi0"].T, origin="lower", cmap="viridis",
                  vmin=0, vmax=1)
        if r["psi"] is not None:
            ax.contour(r["psi"].T, levels=[0.5], colors="r",
                       linewidths=1.0)
        ax.set_title(f"{label}\ncontrast {r['contrast']:+.2f}",
                     fontsize=11)
        ax.set_xticks([]); ax.set_yticks([])
    fig.suptitle("Same coupling up the (M,K) ladder", fontsize=12,
                 y=1.03)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def write_numbers(on, off, ladder):
    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"
    r31 = ladder[0][1]; r32 = ladder[1][1]
    lines = ["% AUTO-GENERATED by gen_figures.py - do not edit.",
             mac("PsevenInside", f"{on['inside']:.3f}"),
             mac("PsevenOutside", f"{on['outside']:.3f}"),
             mac("PsevenContrastOn", f"{on['contrast']:+.3f}"),
             mac("PsevenContrastOff", f"{off['contrast']:+.3f}"),
             mac("PsevenAmplify",
                 f"{on['contrast'] / max(off['contrast'], 0.02):.0f}"),
             mac("PsevenAreaOn", f"{on['area_end']:.3f}"),
             mac("PsevenContrastThreeone", f"{r31['contrast']:+.3f}"),
             mac("PsevenContrastThreetwo", f"{r32['contrast']:+.3f}")]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    ap.add_argument("--level", type=int, default=6)
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    dm, mesh, cons = build_mesh_dm(args.level, device=args.device)
    on = run(dm, mesh, cons, M=2, K=1, crystallize=True,
             device=args.device)
    off = run(dm, mesh, cons, M=2, K=1, crystallize=False,
              device=args.device)
    ladder = [("(M,K)=(3,1)", run(dm, mesh, cons, M=3, K=1,
                                  crystallize=True, device=args.device)),
              ("(M,K)=(3,2)", run(dm, mesh, cons, M=3, K=2,
                                  crystallize=True, device=args.device))]
    fig_demix(on, off, "p7_demixing.png")
    fig_ladder([("(M,K)=(2,1)", on)] + ladder, "p7_ladder.png")
    write_numbers(on, off, ladder)


if __name__ == "__main__":
    main()
