"""OrgElMorph course - Computational C2: figures + numbers.

Writes a two-panel field figure (no-flux vs Dirichlet) and a mass-vs-time
figure into ../../latex/figures/, and the measured macros into
../../latex/numbers/c2.tex.  Same core as run.py.

    PYTHONPATH=<repo>/src python gen_figures.py --device cuda:0
"""
import argparse
import os

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from bc import compare, DT

FIGDIR = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "figures")
NUMTEX = os.path.join(os.path.dirname(__file__),
                      "..", "..", "latex", "numbers", "c2.tex")


def fields_figure(r, fname):
    nf, di = r["noflux"], r["dirichlet"]
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 4.3), dpi=150)
    for ax, rec, title in ((axes[0], nf, "natural (no-flux)"),
                           (axes[1], di,
                            f"Dirichlet (wall $c={di['wall']:.1f}$)")):
        im = ax.imshow(rec["img"], origin="lower", cmap="RdBu_r",
                       vmin=-1, vmax=1)
        ax.set_title(title, fontsize=11)
        ax.set_xticks([]); ax.set_yticks([])
    fig.colorbar(im, ax=axes, fraction=0.023, pad=0.02, label="c")
    fig.suptitle("Same blend, two boundary conditions "
                 "-- the wall pins the Dirichlet field", y=1.0)
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def mass_figure(r, fname):
    nf, di = r["noflux"], r["dirichlet"]
    fig, ax = plt.subplots(figsize=(6.4, 4.3), dpi=150)
    for rec, col, lab in ((nf, "C0", "no-flux (conserved)"),
                          (di, "C3", "Dirichlet (reservoir)")):
        t = np.arange(len(rec["masses"])) * DT
        ax.plot(t, rec["masses"] - rec["masses"][0], col + "-", lw=2,
                label=lab)
    ax.set_xlabel("time $t$")
    ax.set_ylabel(r"mass change $m(t)-m(0)$")
    ax.set_title("Mass conservation depends on the boundary condition")
    ax.grid(alpha=0.3); ax.legend()
    fig.savefig(os.path.join(FIGDIR, fname), bbox_inches="tight",
                facecolor="white")
    plt.close(fig)
    print("wrote", fname)


def sci(val):
    m, e = f"{val:.1e}".split("e")
    return rf"${m}\times10^{{{int(e)}}}$"


def write_numbers(r):
    nf, di = r["noflux"], r["dirichlet"]

    def mac(name, val):
        return rf"\newcommand{{\{name}}}{{{val}}}"

    lines = [
        "% AUTO-GENERATED by gen_figures.py - do not edit.",
        mac("CtwoWall", f"{di['wall']:.1f}"),
        mac("CtwoNfMassDrift", sci(nf["mass_drift"])),
        mac("CtwoNfEdge", f"{nf['edge_mean']:+.2f}"),
        mac("CtwoDirMassDrift", f"{di['mass_drift']:.2f}"),
        mac("CtwoDirEdge", f"{di['edge_mean']:+.2f}"),
        mac("CtwoFieldDiff", f"{r['field_diff']:.2f}"),
    ]
    os.makedirs(os.path.dirname(NUMTEX), exist_ok=True)
    with open(NUMTEX, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", NUMTEX)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda:0")
    args = ap.parse_args()
    os.makedirs(FIGDIR, exist_ok=True)
    r = compare(device=args.device)
    fields_figure(r, "c2_fields.png")
    mass_figure(r, "c2_mass.png")
    write_numbers(r)


if __name__ == "__main__":
    main()
